INFO 2023-09-28 06:27:41,966 autoreload 12780 13296 Watching for file changes with StatReloader
INFO 2023-09-28 18:46:17,626 autoreload 15672 15444 Watching for file changes with StatReloader
INFO 2023-09-28 18:46:19,919 views 15672 18164 Index page accessed
INFO 2023-09-28 18:46:19,935 basehttp 15672 18164 "GET / HTTP/1.1" 200 10730
WARNING 2023-09-28 18:46:20,186 log 15672 18164 Not Found: /favicon.ico
WARNING 2023-09-28 18:46:20,186 basehttp 15672 18164 "GET /favicon.ico HTTP/1.1" 404 3498
INFO 2023-09-28 18:46:22,193 views 15672 18164 Index page accessed
INFO 2023-09-28 18:46:22,197 basehttp 15672 18164 "GET / HTTP/1.1" 200 10730
DEBUG 2023-09-28 18:46:24,517 views 15672 9580 Info page accessed
INFO 2023-09-28 18:46:24,518 basehttp 15672 9580 "GET /info/ HTTP/1.1" 200 2885
DEBUG 2023-09-28 18:46:27,523 views 15672 9580 About page accessed
INFO 2023-09-28 18:46:27,525 basehttp 15672 9580 "GET /about/ HTTP/1.1" 200 2884
INFO 2023-09-28 18:46:28,424 views 15672 9580 Index page accessed
INFO 2023-09-28 18:46:28,427 basehttp 15672 9580 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 18:46:36,996 basehttp 15672 9580 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 18:46:37,998 basehttp 15672 9580 "GET /account/registration/ HTTP/1.1" 200 4035
INFO 2023-09-28 18:46:41,724 basehttp 15672 9580 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 18:46:43,092 basehttp 15672 9580 "GET /account/registration/ HTTP/1.1" 200 4035
INFO 2023-09-28 18:46:43,944 views 15672 9580 Index page accessed
INFO 2023-09-28 18:46:43,947 basehttp 15672 9580 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 18:46:44,896 basehttp 15672 9580 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 18:46:46,162 basehttp 15672 9580 "GET /account/registration/ HTTP/1.1" 200 4035
INFO 2023-09-28 18:46:57,115 views 15672 9580 Registration new user: username='test', email='test@test.ru', password='test'.
INFO 2023-09-28 18:46:57,122 basehttp 15672 9580 "POST /account/registration/ HTTP/1.1" 200 4068
INFO 2023-09-28 18:47:12,422 basehttp 15672 9580 "GET /admin/ HTTP/1.1" 302 0
INFO 2023-09-28 18:47:12,449 basehttp 15672 9580 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4267
INFO 2023-09-28 18:47:12,488 basehttp 15672 9580 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2023-09-28 18:47:12,495 basehttp 15672 9580 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2023-09-28 18:47:12,497 basehttp 15672 15208 "GET /static/admin/css/login.css HTTP/1.1" 304 0
INFO 2023-09-28 18:47:12,497 basehttp 15672 18032 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2023-09-28 18:47:12,497 basehttp 15672 3192 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2023-09-28 18:47:12,499 basehttp 15672 9068 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2023-09-28 18:47:12,499 basehttp 15672 7452 "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2023-09-28 18:47:15,982 basehttp 15672 7452 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4534
INFO 2023-09-28 18:47:21,923 basehttp 15672 7452 "POST /admin/login/?next=/admin/ HTTP/1.1" 200 4533
INFO 2023-09-28 18:47:30,700 views 15672 7452 Index page accessed
INFO 2023-09-28 18:47:30,702 basehttp 15672 7452 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 18:47:33,334 basehttp 15672 7452 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 18:47:42,734 views 15672 7452 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 18:47:42,737 views 15672 7452 Login successful
INFO 2023-09-28 18:47:42,740 basehttp 15672 7452 "POST /account/login HTTP/1.1" 200 3651
INFO 2023-09-28 18:47:48,969 views 15672 7452 Index page accessed
INFO 2023-09-28 18:47:48,972 basehttp 15672 7452 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 18:48:07,661 basehttp 15672 7452 "GET /account/upload/ HTTP/1.1" 200 3258
INFO 2023-09-28 18:48:16,673 basehttp 15672 7452 "GET /account/forms/ HTTP/1.1" 200 4825
INFO 2023-09-28 18:48:22,507 views 15672 7452 Index page accessed
INFO 2023-09-28 18:48:22,510 basehttp 15672 7452 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 19:08:38,668 autoreload 15672 15444 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:08:39,262 autoreload 11588 19424 Watching for file changes with StatReloader
INFO 2023-09-28 19:12:28,496 autoreload 11588 19424 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:12:29,019 autoreload 12136 6204 Watching for file changes with StatReloader
INFO 2023-09-28 19:12:38,752 autoreload 12136 6204 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:12:39,222 autoreload 12832 11468 Watching for file changes with StatReloader
INFO 2023-09-28 19:13:12,728 autoreload 12832 11468 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:13:13,212 autoreload 17524 11940 Watching for file changes with StatReloader
INFO 2023-09-28 19:35:28,676 autoreload 17524 11940 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:35:29,164 autoreload 6472 6584 Watching for file changes with StatReloader
INFO 2023-09-28 19:47:57,099 autoreload 6472 6584 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:47:57,598 autoreload 4524 4244 Watching for file changes with StatReloader
WARNING 2023-09-28 19:48:08,401 log 4524 15120 Not Found: /account/login/
WARNING 2023-09-28 19:48:08,402 basehttp 4524 15120 "POST /account/login/ HTTP/1.1" 404 4132
WARNING 2023-09-28 19:50:06,427 log 4524 15120 Not Found: /account/login/
WARNING 2023-09-28 19:50:06,427 basehttp 4524 15120 "GET /account/login/ HTTP/1.1" 404 4131
WARNING 2023-09-28 19:50:07,625 log 4524 15120 Not Found: /account/login/
WARNING 2023-09-28 19:50:07,625 basehttp 4524 15120 "GET /account/login/ HTTP/1.1" 404 4131
WARNING 2023-09-28 19:50:16,442 log 4524 15120 Not Found: /login
WARNING 2023-09-28 19:50:16,442 basehttp 4524 15120 "GET /login HTTP/1.1" 404 3480
INFO 2023-09-28 19:50:19,338 views 4524 15120 Index page accessed
INFO 2023-09-28 19:50:19,351 basehttp 4524 15120 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 19:50:20,391 basehttp 4524 15120 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 19:50:35,999 views 4524 15120 Try login: email='test@tt.ru', password='qwer'.
INFO 2023-09-28 19:50:36,002 views 4524 15120 Login failed
INFO 2023-09-28 19:50:36,005 basehttp 4524 15120 "POST /account/login HTTP/1.1" 200 3647
INFO 2023-09-28 19:50:55,784 views 4524 15120 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 19:50:55,787 views 4524 15120 Login successful
ERROR 2023-09-28 19:50:55,814 log 4524 15120 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 62, in login_form
    user = SettingsBackend.get_user(user.pk)
TypeError: SettingsBackend.get_user() missing 1 required positional argument: 'user_id'
ERROR 2023-09-28 19:50:55,816 basehttp 4524 15120 "POST /account/login HTTP/1.1" 500 71009
INFO 2023-09-28 19:51:28,430 autoreload 4524 4244 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:51:28,904 autoreload 13432 11200 Watching for file changes with StatReloader
INFO 2023-09-28 19:51:32,991 views 13432 2020 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 19:51:32,993 views 13432 2020 Login successful
ERROR 2023-09-28 19:51:33,024 log 13432 2020 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 62, in login_form
    user = SettingsBackend.get_user(user.id)
TypeError: SettingsBackend.get_user() missing 1 required positional argument: 'user_id'
ERROR 2023-09-28 19:51:33,025 basehttp 13432 2020 "POST /account/login HTTP/1.1" 500 71009
INFO 2023-09-28 19:51:59,710 autoreload 13432 11200 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:52:00,212 autoreload 3304 17344 Watching for file changes with StatReloader
INFO 2023-09-28 19:52:06,865 basehttp 3304 14496 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 19:52:13,376 views 3304 14496 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 19:52:13,379 views 3304 14496 Login successful
ERROR 2023-09-28 19:52:13,409 log 3304 14496 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 62, in login_form
    user = SettingsBackend.get_user(user_id=user.id)
TypeError: SettingsBackend.get_user() missing 1 required positional argument: 'self'
ERROR 2023-09-28 19:52:13,410 basehttp 3304 14496 "POST /account/login HTTP/1.1" 500 71013
INFO 2023-09-28 19:52:36,604 autoreload 3304 17344 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:52:37,083 autoreload 14988 17088 Watching for file changes with StatReloader
INFO 2023-09-28 19:52:39,592 views 14988 10856 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 19:52:39,594 views 14988 10856 Login successful
ERROR 2023-09-28 19:52:39,626 log 14988 10856 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 63, in login_form
    message = f"Welcome, {user.username}"
AttributeError: 'NoneType' object has no attribute 'username'
ERROR 2023-09-28 19:52:39,627 basehttp 14988 10856 "POST /account/login HTTP/1.1" 500 70791
INFO 2023-09-28 19:53:16,220 autoreload 14988 17088 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:53:16,714 autoreload 12036 11712 Watching for file changes with StatReloader
INFO 2023-09-28 19:53:19,149 views 12036 12940 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 19:53:19,152 views 12036 12940 Login successful
INFO 2023-09-28 19:53:19,169 basehttp 12036 12940 "POST /account/login HTTP/1.1" 200 3654
INFO 2023-09-28 19:53:45,579 autoreload 12036 11712 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:53:46,072 autoreload 10608 3384 Watching for file changes with StatReloader
INFO 2023-09-28 19:53:47,433 views 10608 17476 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 19:53:47,436 views 10608 17476 Login successful
INFO 2023-09-28 19:53:47,451 basehttp 10608 17476 "POST /account/login HTTP/1.1" 200 3654
INFO 2023-09-28 19:53:57,105 autoreload 10608 3384 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:53:57,577 autoreload 3408 18732 Watching for file changes with StatReloader
INFO 2023-09-28 19:53:59,000 views 3408 768 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 19:53:59,002 views 3408 768 Login successful
INFO 2023-09-28 19:53:59,016 basehttp 3408 768 "POST /account/login HTTP/1.1" 200 3654
INFO 2023-09-28 19:54:02,980 views 3408 768 Index page accessed
INFO 2023-09-28 19:54:02,986 basehttp 3408 768 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 19:54:04,408 basehttp 3408 768 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 19:54:11,194 views 3408 768 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 19:54:11,197 views 3408 768 Login successful
INFO 2023-09-28 19:54:11,200 basehttp 3408 768 "POST /account/login HTTP/1.1" 200 3654
INFO 2023-09-28 19:55:18,590 autoreload 3408 18732 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:55:19,049 autoreload 19072 16928 Watching for file changes with StatReloader
INFO 2023-09-28 19:55:21,371 views 19072 9616 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 19:55:21,374 views 19072 9616 Login successful
INFO 2023-09-28 19:55:21,387 basehttp 19072 9616 "POST /account/login HTTP/1.1" 200 3654
INFO 2023-09-28 19:56:06,615 autoreload 19072 16928 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:56:07,074 autoreload 11876 14760 Watching for file changes with StatReloader
INFO 2023-09-28 19:56:10,392 views 11876 18164 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 19:56:10,394 views 11876 18164 Login successful
ERROR 2023-09-28 19:56:10,425 log 11876 18164 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 63, in login_form
    user = SettingsBackend.get_user(user.id)
AttributeError: 'NoneType' object has no attribute 'id'
ERROR 2023-09-28 19:56:10,427 basehttp 11876 18164 "POST /account/login HTTP/1.1" 500 70814
INFO 2023-09-28 19:56:34,806 autoreload 11876 14760 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:56:35,293 autoreload 13972 2512 Watching for file changes with StatReloader
INFO 2023-09-28 19:56:36,710 views 13972 5620 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 19:56:36,713 views 13972 5620 Login successful
ERROR 2023-09-28 19:56:36,747 log 13972 5620 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 64, in login_form
    user = SettingsBackend.get_user(user.id)
AttributeError: 'NoneType' object has no attribute 'id'
ERROR 2023-09-28 19:56:36,748 basehttp 13972 5620 "POST /account/login HTTP/1.1" 500 70788
INFO 2023-09-28 19:57:34,293 autoreload 13972 2512 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:57:34,759 autoreload 4184 9484 Watching for file changes with StatReloader
INFO 2023-09-28 19:57:40,680 views 4184 17200 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 19:57:40,683 views 4184 17200 Login successful
ERROR 2023-09-28 19:57:40,716 log 4184 17200 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 65, in login_form
    user = SettingsBackend.get_user(user.id)
AttributeError: 'NoneType' object has no attribute 'id'
ERROR 2023-09-28 19:57:40,716 basehttp 4184 17200 "POST /account/login HTTP/1.1" 500 70788
INFO 2023-09-28 19:59:12,408 autoreload 4184 9484 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:59:12,897 autoreload 4724 1376 Watching for file changes with StatReloader
INFO 2023-09-28 19:59:16,694 views 4724 18132 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 19:59:16,696 views 4724 18132 Login successful
ERROR 2023-09-28 19:59:16,728 log 4724 18132 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 64, in login_form
    user = SettingsBackend.authenticate(email, password)
  File "E:\pythonProject\djangoGB\account\views.py", line 25, in authenticate
    user = AuthUser.objects.get(username=username)
NameError: name 'username' is not defined
ERROR 2023-09-28 19:59:16,730 basehttp 4724 18132 "POST /account/login HTTP/1.1" 500 74970
INFO 2023-09-28 19:59:53,183 autoreload 4724 1376 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 19:59:53,684 autoreload 5000 4140 Watching for file changes with StatReloader
INFO 2023-09-28 19:59:56,344 views 5000 19276 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 19:59:56,347 views 5000 19276 Login successful
ERROR 2023-09-28 19:59:56,379 log 5000 19276 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 64, in login_form
    user = SettingsBackend.authenticate(user.email, user.password)
  File "E:\pythonProject\djangoGB\account\views.py", line 25, in authenticate
    user = AuthUser.objects.get(username=username)
NameError: name 'username' is not defined
ERROR 2023-09-28 19:59:56,381 basehttp 5000 19276 "POST /account/login HTTP/1.1" 500 74990
INFO 2023-09-28 20:00:43,363 autoreload 5000 4140 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 20:00:43,841 autoreload 10436 17940 Watching for file changes with StatReloader
INFO 2023-09-28 20:00:45,264 views 10436 9904 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 20:00:45,267 views 10436 9904 Login successful
ERROR 2023-09-28 20:00:45,302 log 10436 9904 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 64, in login_form
    user = SettingsBackend.authenticate(user.get('email'), user.get("password"))
AttributeError: 'User' object has no attribute 'get'
ERROR 2023-09-28 20:00:45,303 basehttp 10436 9904 "POST /account/login HTTP/1.1" 500 71000
INFO 2023-09-28 20:01:24,164 autoreload 10436 17940 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 20:01:24,642 autoreload 10328 15464 Watching for file changes with StatReloader
INFO 2023-09-28 20:01:36,267 autoreload 10328 15464 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 20:01:36,722 autoreload 9680 17404 Watching for file changes with StatReloader
INFO 2023-09-28 20:01:42,303 views 9680 1820 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 20:01:42,306 views 9680 1820 Login successful
ERROR 2023-09-28 20:01:42,340 log 9680 1820 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 65, in login_form
    user = SettingsBackend.authenticate(user['email'], user["password"])
TypeError: 'User' object is not subscriptable
ERROR 2023-09-28 20:01:42,341 basehttp 9680 1820 "POST /account/login HTTP/1.1" 500 70886
INFO 2023-09-28 20:03:56,103 autoreload 9680 17404 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 20:03:56,586 autoreload 9604 15052 Watching for file changes with StatReloader
INFO 2023-09-28 20:03:58,628 views 9604 6340 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 20:03:58,630 views 9604 6340 Login successful
ERROR 2023-09-28 20:03:58,661 log 9604 6340 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 66, in login_form
    user = SettingsBackend.authenticate(user['email'], user["password"])
TypeError: 'User' object is not subscriptable
ERROR 2023-09-28 20:03:58,662 basehttp 9604 6340 "POST /account/login HTTP/1.1" 500 70928
INFO 2023-09-28 20:04:58,683 autoreload 9604 15052 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 20:04:59,179 autoreload 4320 2112 Watching for file changes with StatReloader
INFO 2023-09-28 20:05:01,920 views 4320 14560 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 20:05:01,922 views 4320 14560 Login successful
ERROR 2023-09-28 20:05:01,955 log 4320 14560 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 66, in login_form
    user_auth = SettingsBackend.authenticate(user.email, user.password)
  File "E:\pythonProject\djangoGB\account\views.py", line 25, in authenticate
    user = AuthUser.objects.get(username=username)
NameError: name 'username' is not defined
ERROR 2023-09-28 20:05:01,956 basehttp 4320 14560 "POST /account/login HTTP/1.1" 500 75121
INFO 2023-09-28 20:05:57,121 autoreload 4320 2112 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 20:05:57,594 autoreload 11976 6628 Watching for file changes with StatReloader
INFO 2023-09-28 20:05:59,886 views 11976 13516 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 20:05:59,889 views 11976 13516 Login successful
ERROR 2023-09-28 20:05:59,921 log 11976 13516 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 66, in login_form
    user_auth = SettingsBackend.authenticate(email=user.email, password=user.password)
TypeError: SettingsBackend.authenticate() missing 2 required positional arguments: 'self' and 'request'
ERROR 2023-09-28 20:05:59,922 basehttp 11976 13516 "POST /account/login HTTP/1.1" 500 71287
INFO 2023-09-28 20:06:30,568 autoreload 11976 6628 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 20:06:31,032 autoreload 12804 17528 Watching for file changes with StatReloader
INFO 2023-09-28 20:06:34,139 views 12804 15172 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 20:06:34,142 views 12804 15172 Login successful
ERROR 2023-09-28 20:06:34,174 log 12804 15172 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 66, in login_form
    user_auth = SettingsBackend.authenticate(request, email=user.email, password=user.password)
TypeError: SettingsBackend.authenticate() missing 1 required positional argument: 'request'
ERROR 2023-09-28 20:06:34,175 basehttp 12804 15172 "POST /account/login HTTP/1.1" 500 71217
INFO 2023-09-28 20:06:48,268 autoreload 12804 17528 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 20:06:48,742 autoreload 17316 6368 Watching for file changes with StatReloader
INFO 2023-09-28 20:06:49,942 views 17316 2608 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 20:06:49,945 views 17316 2608 Login successful
ERROR 2023-09-28 20:06:49,976 log 17316 2608 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 66, in login_form
    user_auth = SettingsBackend.authenticate(user, request, email=user.email, password=user.password)
  File "E:\pythonProject\djangoGB\account\views.py", line 25, in authenticate
    user = AuthUser.objects.get(username=username)
NameError: name 'username' is not defined
ERROR 2023-09-28 20:06:49,977 basehttp 17316 2608 "POST /account/login HTTP/1.1" 500 75355
INFO 2023-09-28 20:07:39,279 autoreload 17316 6368 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 20:07:39,753 autoreload 692 9876 Watching for file changes with StatReloader
INFO 2023-09-28 20:07:44,353 views 692 12580 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 20:07:44,355 views 692 12580 Login successful
ERROR 2023-09-28 20:07:44,388 log 692 12580 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 67, in login_form
    user = SettingsBackend.get_user(user.pk)
TypeError: SettingsBackend.get_user() missing 1 required positional argument: 'user_id'
ERROR 2023-09-28 20:07:44,389 basehttp 692 12580 "POST /account/login HTTP/1.1" 500 71224
INFO 2023-09-28 20:08:13,695 autoreload 692 9876 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 20:08:14,170 autoreload 18012 15604 Watching for file changes with StatReloader
INFO 2023-09-28 20:08:20,608 views 18012 1912 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 20:08:20,610 views 18012 1912 Login successful
ERROR 2023-09-28 20:08:20,642 log 18012 1912 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 67, in login_form
    user = SettingsBackend.get_user(user_auth, user_auth.pk)
AttributeError: 'NoneType' object has no attribute 'pk'
ERROR 2023-09-28 20:08:20,643 basehttp 18012 1912 "POST /account/login HTTP/1.1" 500 71178
INFO 2023-09-28 20:08:55,379 autoreload 18012 15604 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 20:08:55,870 autoreload 9788 12464 Watching for file changes with StatReloader
INFO 2023-09-28 20:08:57,475 views 9788 3904 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 20:08:57,478 views 9788 3904 Login successful
ERROR 2023-09-28 20:08:57,511 log 9788 3904 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 69, in login_form
    message = f"Welcome, {user.username}"
AttributeError: 'NoneType' object has no attribute 'username'
ERROR 2023-09-28 20:08:57,512 basehttp 9788 3904 "POST /account/login HTTP/1.1" 500 70998
INFO 2023-09-28 20:11:53,880 autoreload 9788 12464 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 20:11:54,351 autoreload 15372 12144 Watching for file changes with StatReloader
INFO 2023-09-28 20:11:55,982 views 15372 10892 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 20:11:55,986 views 15372 10892 Login successful
ERROR 2023-09-28 20:11:56,019 log 15372 10892 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 69, in login_form
    message = f"Welcome, {user.username}"
AttributeError: 'NoneType' object has no attribute 'username'
ERROR 2023-09-28 20:11:56,020 basehttp 15372 10892 "POST /account/login HTTP/1.1" 500 71124
INFO 2023-09-28 20:12:34,595 autoreload 15372 12144 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 20:12:35,081 autoreload 11368 10212 Watching for file changes with StatReloader
INFO 2023-09-28 20:12:36,859 views 11368 17328 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 20:12:36,862 views 11368 17328 Login successful
INFO 2023-09-28 20:12:36,877 basehttp 11368 17328 "POST /account/login HTTP/1.1" 200 3651
INFO 2023-09-28 20:12:44,378 views 11368 17328 Index page accessed
INFO 2023-09-28 20:12:44,384 basehttp 11368 17328 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 20:12:45,752 basehttp 11368 17328 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 20:12:47,023 basehttp 11368 17328 "GET /account/registration/ HTTP/1.1" 200 4035
INFO 2023-09-28 20:12:48,008 views 11368 17328 Index page accessed
INFO 2023-09-28 20:12:48,011 basehttp 11368 17328 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 20:13:27,608 basehttp 11368 17328 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 20:13:28,822 views 11368 17328 Index page accessed
INFO 2023-09-28 20:13:28,825 basehttp 11368 17328 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 20:18:18,518 autoreload 11368 10212 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 20:18:19,001 autoreload 11076 19280 Watching for file changes with StatReloader
INFO 2023-09-28 21:17:52,567 autoreload 11076 19280 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 21:17:53,043 autoreload 10320 10544 Watching for file changes with StatReloader
INFO 2023-09-28 21:17:59,525 views 10320 4916 Index page accessed
INFO 2023-09-28 21:17:59,535 basehttp 10320 4916 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 21:18:00,396 basehttp 10320 4916 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 21:18:09,326 views 10320 17988 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 21:18:09,329 views 10320 17988 Login successful
ERROR 2023-09-28 21:18:09,357 log 10320 17988 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 68, in login_form
    message = f"Welcome, {user.username}"
AttributeError: 'NoneType' object has no attribute 'username'
ERROR 2023-09-28 21:18:09,358 basehttp 10320 17988 "POST /account/login HTTP/1.1" 500 70841
INFO 2023-09-28 21:19:17,355 autoreload 10320 10544 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 21:19:17,842 autoreload 10416 2416 Watching for file changes with StatReloader
INFO 2023-09-28 21:19:19,721 views 10416 11236 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 21:19:19,724 views 10416 11236 Login successful
INFO 2023-09-28 21:19:19,738 basehttp 10416 11236 "POST /account/login HTTP/1.1" 200 3654
INFO 2023-09-28 21:20:13,773 autoreload 10416 2416 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 21:20:14,242 autoreload 8972 14012 Watching for file changes with StatReloader
INFO 2023-09-28 21:20:15,329 views 8972 19312 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 21:20:15,331 views 8972 19312 Login successful
INFO 2023-09-28 21:20:15,346 basehttp 8972 19312 "POST /account/login HTTP/1.1" 200 3654
INFO 2023-09-28 21:20:59,476 autoreload 8972 14012 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 21:20:59,960 autoreload 5100 10712 Watching for file changes with StatReloader
INFO 2023-09-28 21:21:01,971 views 5100 19276 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 21:21:01,973 views 5100 19276 Login successful
INFO 2023-09-28 21:21:01,988 basehttp 5100 19276 "POST /account/login HTTP/1.1" 200 3651
INFO 2023-09-28 21:21:23,519 autoreload 5100 10712 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 21:21:24,024 autoreload 14536 10552 Watching for file changes with StatReloader
INFO 2023-09-28 21:21:26,565 views 14536 15480 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 21:21:26,567 views 14536 15480 Login successful
ERROR 2023-09-28 21:21:26,599 log 14536 15480 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 72, in login_form
    print(user.is_authenticated)
AttributeError: 'User' object has no attribute 'is_authenticated'
ERROR 2023-09-28 21:21:26,601 basehttp 14536 15480 "POST /account/login HTTP/1.1" 500 71067
INFO 2023-09-28 21:22:27,329 autoreload 14536 10552 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 21:22:27,800 autoreload 17884 2748 Watching for file changes with StatReloader
INFO 2023-09-28 21:22:30,358 views 17884 7116 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 21:22:30,360 views 17884 7116 Login successful
INFO 2023-09-28 21:22:30,375 basehttp 17884 7116 "POST /account/login HTTP/1.1" 200 3647
INFO 2023-09-28 21:22:34,688 views 17884 8300 Index page accessed
INFO 2023-09-28 21:22:34,694 basehttp 17884 8300 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 21:22:41,575 views 17884 17960 Index page accessed
INFO 2023-09-28 21:22:41,577 basehttp 17884 17960 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 21:22:42,657 views 17884 17960 Index page accessed
INFO 2023-09-28 21:22:42,660 basehttp 17884 17960 "GET / HTTP/1.1" 200 10730
WARNING 2023-09-28 21:23:16,582 log 17884 18796 Forbidden (CSRF token missing.): /
WARNING 2023-09-28 21:23:16,583 basehttp 17884 18796 "POST / HTTP/1.1" 403 2548
INFO 2023-09-28 21:23:18,166 views 17884 18796 Index page accessed
INFO 2023-09-28 21:23:18,169 basehttp 17884 18796 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 21:23:19,373 views 17884 18796 Index page accessed
INFO 2023-09-28 21:23:19,376 basehttp 17884 18796 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 21:23:20,532 views 17884 18796 Index page accessed
INFO 2023-09-28 21:23:20,534 basehttp 17884 18796 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 21:24:36,925 autoreload 17884 2748 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 21:24:37,413 autoreload 18600 1096 Watching for file changes with StatReloader
INFO 2023-09-28 21:24:39,191 views 18600 17464 Index page accessed
INFO 2023-09-28 21:24:39,201 basehttp 18600 17464 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 21:24:42,016 basehttp 18600 17464 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 21:24:48,311 views 18600 17464 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 21:24:48,313 views 18600 17464 Login successful
INFO 2023-09-28 21:24:48,317 basehttp 18600 17464 "POST /account/login HTTP/1.1" 200 3651
INFO 2023-09-28 21:24:54,984 views 18600 12180 Index page accessed
INFO 2023-09-28 21:24:54,987 basehttp 18600 12180 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 21:25:02,943 basehttp 18600 12180 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 21:25:50,690 views 18600 11440 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 21:25:50,692 views 18600 11440 Login successful
INFO 2023-09-28 21:25:50,696 basehttp 18600 11440 "POST /account/login HTTP/1.1" 200 3651
INFO 2023-09-28 21:34:11,126 autoreload 18600 1096 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 21:34:11,606 autoreload 17296 14712 Watching for file changes with StatReloader
INFO 2023-09-28 21:34:13,809 views 17296 8276 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 21:34:13,812 views 17296 8276 Login successful
ERROR 2023-09-28 21:34:13,842 log 17296 8276 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 65, in login_form
    user.SettingsBackend.authenticate(request, username=user.username, password=user.password)
AttributeError: 'User' object has no attribute 'SettingsBackend'
ERROR 2023-09-28 21:34:13,844 basehttp 17296 8276 "POST /account/login HTTP/1.1" 500 71206
INFO 2023-09-28 22:34:29,669 views 17296 14416 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 22:34:29,671 views 17296 14416 Login successful
ERROR 2023-09-28 22:34:29,690 log 17296 14416 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 65, in login_form
    user.SettingsBackend.authenticate(request, username=user.username, password=user.password)
AttributeError: 'User' object has no attribute 'SettingsBackend'
ERROR 2023-09-28 22:34:29,691 basehttp 17296 14416 "POST /account/login HTTP/1.1" 500 71206
INFO 2023-09-28 22:45:21,912 autoreload 19328 11892 Watching for file changes with StatReloader
INFO 2023-09-28 22:45:23,098 views 19328 12260 Index page accessed
INFO 2023-09-28 22:45:23,110 basehttp 19328 12260 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 22:45:24,784 basehttp 19328 12260 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 22:45:30,712 views 19328 12260 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 22:45:30,715 views 19328 12260 Login successful
ERROR 2023-09-28 22:45:30,744 log 19328 12260 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 67, in login_form
    user = authenticate(request, username=user.username, password=user.password)
NameError: name 'authenticate' is not defined
ERROR 2023-09-28 22:45:30,745 basehttp 19328 12260 "POST /account/login HTTP/1.1" 500 71054
INFO 2023-09-28 22:45:44,400 autoreload 19328 11892 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 22:45:44,870 autoreload 9904 1308 Watching for file changes with StatReloader
INFO 2023-09-28 22:45:46,526 views 9904 16912 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 22:45:46,528 views 9904 16912 Login successful
ERROR 2023-09-28 22:45:46,560 log 9904 16912 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 67, in login_form
    user = SettingsBackend.authenticate(request, username=user.username, password=user.password)
TypeError: SettingsBackend.authenticate() missing 1 required positional argument: 'request'
ERROR 2023-09-28 22:45:46,561 basehttp 9904 16912 "POST /account/login HTTP/1.1" 500 71270
INFO 2023-09-28 22:46:27,182 autoreload 9904 1308 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 22:46:27,645 autoreload 7716 15632 Watching for file changes with StatReloader
INFO 2023-09-28 22:46:29,127 views 7716 5112 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 22:46:29,129 views 7716 5112 Login successful
ERROR 2023-09-28 22:46:29,160 log 7716 5112 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 67, in login_form
    user.SettingsBackend.authenticate(request, username=user.username, password=user.password)
AttributeError: 'User' object has no attribute 'SettingsBackend'
ERROR 2023-09-28 22:46:29,162 basehttp 7716 5112 "POST /account/login HTTP/1.1" 500 71208
INFO 2023-09-28 22:48:49,075 autoreload 7716 15632 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 22:48:49,530 autoreload 5084 17344 Watching for file changes with StatReloader
INFO 2023-09-28 22:48:52,976 views 5084 12920 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 22:48:52,978 views 5084 12920 Login successful
ERROR 2023-09-28 22:48:53,008 log 5084 12920 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 67, in login_form
    AuthUser.SettingsBackend.authenticate(request, username=user.username, password=user.password)
AttributeError: type object 'User' has no attribute 'SettingsBackend'
ERROR 2023-09-28 22:48:53,010 basehttp 5084 12920 "POST /account/login HTTP/1.1" 500 71236
INFO 2023-09-28 22:49:39,129 autoreload 5084 17344 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 22:49:39,599 autoreload 3720 12032 Watching for file changes with StatReloader
INFO 2023-09-28 22:49:42,221 views 3720 17940 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 22:49:42,223 views 3720 17940 Login successful
ERROR 2023-09-28 22:49:42,254 log 3720 17940 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 67, in login_form
    user.authenticate(request, username=user.username, password=user.password)
AttributeError: 'User' object has no attribute 'authenticate'
ERROR 2023-09-28 22:49:42,255 basehttp 3720 17940 "POST /account/login HTTP/1.1" 500 71164
INFO 2023-09-28 23:03:22,887 autoreload 3720 12032 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:03:23,359 autoreload 14840 4044 Watching for file changes with StatReloader
INFO 2023-09-28 23:03:28,175 views 14840 3688 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:03:28,178 views 14840 3688 Login successful
ERROR 2023-09-28 23:03:28,215 log 14840 3688 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 68, in login_form
    login(request, user, backend=SettingsBackend)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 134, in login
    raise TypeError(
TypeError: backend must be a dotted import path string (got <class 'account.views.SettingsBackend'>).
ERROR 2023-09-28 23:03:28,217 basehttp 14840 3688 "POST /account/login HTTP/1.1" 500 75697
INFO 2023-09-28 23:03:57,245 autoreload 14840 4044 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:03:57,739 autoreload 10052 12420 Watching for file changes with StatReloader
INFO 2023-09-28 23:03:58,871 views 10052 12884 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:03:58,873 views 10052 12884 Login successful
ERROR 2023-09-28 23:03:58,909 log 10052 12884 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 70, in login_form
    login(request, user, backend=account.views.SettingsBackend)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 134, in login
    raise TypeError(
TypeError: backend must be a dotted import path string (got <class 'account.views.SettingsBackend'>).
ERROR 2023-09-28 23:03:58,911 basehttp 10052 12884 "POST /account/login HTTP/1.1" 500 75725
INFO 2023-09-28 23:05:26,840 autoreload 10052 12420 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:05:27,331 autoreload 14248 18008 Watching for file changes with StatReloader
INFO 2023-09-28 23:05:31,561 views 14248 8008 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:05:31,563 views 14248 8008 Login successful
ERROR 2023-09-28 23:05:31,594 log 14248 8008 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 70, in login_form
    login(request, user.account.views.SettingsBackend)
AttributeError: 'User' object has no attribute 'account'
ERROR 2023-09-28 23:05:31,595 basehttp 14248 8008 "POST /account/login HTTP/1.1" 500 71143
INFO 2023-09-28 23:05:51,902 autoreload 14248 18008 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:05:52,387 autoreload 15556 19192 Watching for file changes with StatReloader
INFO 2023-09-28 23:05:54,281 views 15556 6440 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:05:54,283 views 15556 6440 Login successful
ERROR 2023-09-28 23:05:54,314 log 15556 6440 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 70, in login_form
    login(request, user.backend.account.views.SettingsBackend)
AttributeError: 'User' object has no attribute 'backend'
ERROR 2023-09-28 23:05:54,315 basehttp 15556 6440 "POST /account/login HTTP/1.1" 500 71159
INFO 2023-09-28 23:06:50,362 autoreload 15556 19192 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:06:50,853 autoreload 17976 12136 Watching for file changes with StatReloader
INFO 2023-09-28 23:06:53,317 views 17976 12552 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:06:53,319 views 17976 12552 Login successful
ERROR 2023-09-28 23:06:53,359 log 17976 12552 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 70, in login_form
    login(request, user, backend=account.views)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 134, in login
    raise TypeError(
TypeError: backend must be a dotted import path string (got <module 'account.views' from 'E:\\pythonProject\\djangoGB\\account\\views.py'>).
ERROR 2023-09-28 23:06:53,360 basehttp 17976 12552 "POST /account/login HTTP/1.1" 500 75946
INFO 2023-09-28 23:07:55,230 autoreload 17976 12136 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:07:55,701 autoreload 6308 12940 Watching for file changes with StatReloader
INFO 2023-09-28 23:07:57,469 views 6308 15040 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:07:57,472 views 6308 15040 Login successful
ERROR 2023-09-28 23:07:57,508 log 6308 15040 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 70, in login_form
    login(request, user, backend=account.views.SettingsBackend())
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 134, in login
    raise TypeError(
TypeError: backend must be a dotted import path string (got <account.views.SettingsBackend object at 0x00000223B8F51C90>).
ERROR 2023-09-28 23:07:57,510 basehttp 6308 15040 "POST /account/login HTTP/1.1" 500 75784
INFO 2023-09-28 23:08:35,965 autoreload 6308 12940 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:08:36,441 autoreload 4304 14108 Watching for file changes with StatReloader
INFO 2023-09-28 23:08:49,095 autoreload 4304 14108 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:08:49,608 autoreload 3244 15592 Watching for file changes with StatReloader
INFO 2023-09-28 23:08:53,125 views 3244 9068 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:08:53,128 views 3244 9068 Login successful
ERROR 2023-09-28 23:08:53,171 log 3244 9068 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 70, in login_form
    login(request, user, backend= 'E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 144, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\base.py", line 797, in save
    raise ValueError(
ValueError: The following fields do not exist in this model, are m2m fields, or are non-concrete fields: last_login
ERROR 2023-09-28 23:08:53,174 basehttp 3244 9068 "POST /account/login HTTP/1.1" 500 93781
INFO 2023-09-28 23:11:01,737 autoreload 3244 15592 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:11:02,264 autoreload 11752 6488 Watching for file changes with StatReloader
INFO 2023-09-28 23:11:02,453 basehttp 11752 1584 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:11:04,983 views 11752 1584 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:11:04,986 views 11752 1584 Login successful
ERROR 2023-09-28 23:11:05,042 log 11752 1584 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\fields\__init__.py", line 2053, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'User'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 71, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 144, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\base_user.py", line 76, in save
    super().save(*args, **kwargs)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\base.py", line 990, in _save_table
    updated = self._do_update(
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\base.py", line 1033, in _do_update
    filtered = base_qs.filter(pk=pk_val)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\query.py", line 1436, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\query.py", line 1454, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\query.py", line 1461, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\sql\query.py", line 1545, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\sql\query.py", line 1576, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\sql\query.py", line 1491, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\sql\query.py", line 1318, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\lookups.py", line 341, in get_prep_lookup
    return super().get_prep_lookup()
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\fields\__init__.py", line 2055, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <User: +---------------------------------------
| username: test
|    email: test@test.ru
|    phone: None
|  address: None>.
ERROR 2023-09-28 23:11:05,048 basehttp 11752 1584 "POST /account/login HTTP/1.1" 500 171617
INFO 2023-09-28 23:12:27,393 autoreload 11752 6488 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:12:27,885 autoreload 3992 3060 Watching for file changes with StatReloader
INFO 2023-09-28 23:12:28,114 basehttp 3992 13880 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:12:31,576 views 3992 13880 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:12:31,578 views 3992 13880 Login successful
ERROR 2023-09-28 23:12:31,619 log 3992 13880 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 71, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 144, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\base_user.py", line 76, in save
    super().save(*args, **kwargs)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\base.py", line 814, in save
    self.save_base(
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\base.py", line 877, in save_base
    updated = self._save_table(
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\base.py", line 967, in _save_table
    raise ValueError("Cannot force an update in save() with no primary key.")
ValueError: Cannot force an update in save() with no primary key.
ERROR 2023-09-28 23:12:31,622 basehttp 3992 13880 "POST /account/login HTTP/1.1" 500 107934
INFO 2023-09-28 23:13:07,124 autoreload 3992 3060 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:13:07,616 autoreload 13608 15468 Watching for file changes with StatReloader
INFO 2023-09-28 23:13:07,859 basehttp 13608 6772 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:13:10,191 views 13608 6772 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:13:10,193 views 13608 6772 Login successful
INFO 2023-09-28 23:13:10,207 basehttp 13608 6772 "POST /account/login HTTP/1.1" 200 3701
INFO 2023-09-28 23:13:12,210 views 13608 6772 Index page accessed
INFO 2023-09-28 23:13:12,218 basehttp 13608 6772 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 23:13:13,838 views 13608 6772 Index page accessed
INFO 2023-09-28 23:13:13,841 basehttp 13608 6772 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 23:13:14,527 views 13608 6772 Index page accessed
INFO 2023-09-28 23:13:14,530 basehttp 13608 6772 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 23:13:18,933 basehttp 13608 6772 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:13:31,179 views 13608 6772 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:13:31,181 views 13608 6772 Login successful
INFO 2023-09-28 23:13:31,192 basehttp 13608 6772 "POST /account/login HTTP/1.1" 200 3701
INFO 2023-09-28 23:13:35,317 views 13608 6772 Index page accessed
INFO 2023-09-28 23:13:35,321 basehttp 13608 6772 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 23:13:41,062 basehttp 13608 6772 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:13:43,435 views 13608 6772 Index page accessed
INFO 2023-09-28 23:13:43,438 basehttp 13608 6772 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 23:15:53,138 autoreload 13608 15468 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:15:53,636 autoreload 6968 9616 Watching for file changes with StatReloader
INFO 2023-09-28 23:15:53,852 basehttp 6968 1380 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:16:00,153 views 6968 1380 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:16:00,156 views 6968 1380 Login successful
INFO 2023-09-28 23:16:00,166 basehttp 6968 1380 "POST /account/login HTTP/1.1" 200 3701
INFO 2023-09-28 23:16:08,227 views 6968 1380 Index page accessed
INFO 2023-09-28 23:16:08,235 basehttp 6968 1380 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 23:16:10,430 views 6968 1380 Index page accessed
INFO 2023-09-28 23:16:10,434 basehttp 6968 1380 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 23:17:03,062 autoreload 6968 9616 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:17:03,552 autoreload 4972 18620 Watching for file changes with StatReloader
INFO 2023-09-28 23:17:03,816 basehttp 4972 13120 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:17:09,447 views 4972 13120 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:17:09,450 views 4972 13120 Login successful
INFO 2023-09-28 23:17:09,461 basehttp 4972 13120 "POST /account/login HTTP/1.1" 200 3701
INFO 2023-09-28 23:17:14,918 views 4972 13120 Index page accessed
INFO 2023-09-28 23:17:14,924 basehttp 4972 13120 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 23:17:16,275 views 4972 13120 Index page accessed
INFO 2023-09-28 23:17:16,278 basehttp 4972 13120 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 23:17:17,847 views 4972 13120 Index page accessed
INFO 2023-09-28 23:17:17,851 basehttp 4972 13120 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 23:19:09,309 autoreload 4972 18620 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:19:09,782 autoreload 15108 6016 Watching for file changes with StatReloader
INFO 2023-09-28 23:20:24,353 autoreload 15108 6016 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:20:24,824 autoreload 8228 7656 Watching for file changes with StatReloader
INFO 2023-09-28 23:20:27,570 basehttp 8228 17288 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:20:34,300 views 8228 17288 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:20:34,588 views 8228 17288 Login successful
ERROR 2023-09-28 23:20:34,624 log 8228 17288 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 72, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 138, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute '_meta'
ERROR 2023-09-28 23:20:34,625 basehttp 8228 17288 "POST /account/login HTTP/1.1" 500 79696
INFO 2023-09-28 23:22:35,189 autoreload 8228 7656 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:22:35,673 autoreload 13712 10912 Watching for file changes with StatReloader
INFO 2023-09-28 23:22:36,593 basehttp 13712 17588 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:22:38,868 views 13712 17588 Try login: email='test@test.ru', password='test'.
ERROR 2023-09-28 23:22:38,900 log 13712 17588 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 69, in login_form
    user = authenticate(request, username=username, password=password)
NameError: name 'username' is not defined
ERROR 2023-09-28 23:22:38,901 basehttp 13712 17588 "POST /account/login HTTP/1.1" 500 71092
INFO 2023-09-28 23:22:59,178 autoreload 13712 10912 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:22:59,647 autoreload 12788 912 Watching for file changes with StatReloader
INFO 2023-09-28 23:23:01,390 views 12788 12004 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:23:01,681 views 12788 12004 Login successful
ERROR 2023-09-28 23:23:01,719 log 12788 12004 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 73, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 138, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute '_meta'
ERROR 2023-09-28 23:23:01,720 basehttp 12788 12004 "POST /account/login HTTP/1.1" 500 79709
INFO 2023-09-28 23:23:58,607 autoreload 12788 912 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:23:59,090 autoreload 10196 5716 Watching for file changes with StatReloader
INFO 2023-09-28 23:24:01,192 views 10196 5736 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:24:01,477 views 10196 5736 Login successful
ERROR 2023-09-28 23:24:01,515 log 10196 5736 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 73, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 138, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute '_meta'
ERROR 2023-09-28 23:24:01,516 basehttp 10196 5736 "POST /account/login HTTP/1.1" 500 79717
INFO 2023-09-28 23:24:27,826 autoreload 10196 5716 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:24:28,311 autoreload 8360 972 Watching for file changes with StatReloader
INFO 2023-09-28 23:24:29,051 views 8360 14772 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:24:29,053 views 8360 14772 Login successful
INFO 2023-09-28 23:24:29,080 basehttp 8360 14772 "POST /account/login HTTP/1.1" 200 3701
INFO 2023-09-28 23:24:46,430 autoreload 8360 972 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:24:46,947 autoreload 7860 14564 Watching for file changes with StatReloader
INFO 2023-09-28 23:24:47,493 views 7860 1280 Try login: email='test@test.ru', password='test'.
ERROR 2023-09-28 23:24:47,811 log 7860 1280 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 71, in login_form
    user = AuthUser(username=user.username, password=user.password, email=user.email, pk=user.id)
AttributeError: 'NoneType' object has no attribute 'username'
ERROR 2023-09-28 23:24:47,812 basehttp 7860 1280 "POST /account/login HTTP/1.1" 500 71492
INFO 2023-09-28 23:36:50,960 autoreload 7860 14564 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:36:51,438 autoreload 4084 15128 Watching for file changes with StatReloader
INFO 2023-09-28 23:36:54,170 basehttp 4084 16988 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:36:57,047 views 4084 16988 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:36:57,049 views 4084 16988 Login successful
ERROR 2023-09-28 23:36:57,084 log 4084 16988 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 73, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 144, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\base.py", line 797, in save
    raise ValueError(
ValueError: The following fields do not exist in this model, are m2m fields, or are non-concrete fields: last_login
ERROR 2023-09-28 23:36:57,087 basehttp 4084 16988 "POST /account/login HTTP/1.1" 500 94207
INFO 2023-09-28 23:39:43,310 autoreload 4084 15128 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:39:43,808 autoreload 17556 17672 Watching for file changes with StatReloader
INFO 2023-09-28 23:39:43,979 basehttp 17556 7956 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:39:46,119 views 17556 7956 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:39:46,406 views 17556 7956 Login successful
ERROR 2023-09-28 23:39:46,442 log 17556 7956 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 74, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 138, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute '_meta'
ERROR 2023-09-28 23:39:46,443 basehttp 17556 7956 "POST /account/login HTTP/1.1" 500 79658
INFO 2023-09-28 23:41:16,271 basehttp 17556 7956 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:41:16,295 autoreload 17556 17672 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:41:16,811 autoreload 8740 14000 Watching for file changes with StatReloader
INFO 2023-09-28 23:41:18,372 views 8740 2872 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:41:18,659 views 8740 2872 Login successful
ERROR 2023-09-28 23:41:18,695 log 8740 2872 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 76, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 138, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute '_meta'
ERROR 2023-09-28 23:41:18,697 basehttp 8740 2872 "POST /account/login HTTP/1.1" 500 79477
INFO 2023-09-28 23:44:41,897 autoreload 8740 14000 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:44:42,379 autoreload 15592 6016 Watching for file changes with StatReloader
INFO 2023-09-28 23:44:46,210 views 15592 11760 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:44:46,498 views 15592 11760 Login successful
ERROR 2023-09-28 23:44:46,536 log 15592 11760 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 90, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 138, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute '_meta'
ERROR 2023-09-28 23:44:46,538 basehttp 15592 11760 "POST /account/login HTTP/1.1" 500 79477
INFO 2023-09-28 23:45:40,738 autoreload 16600 15632 Watching for file changes with StatReloader
INFO 2023-09-28 23:45:47,809 views 15592 11760 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:45:48,093 views 15592 11760 Login successful
ERROR 2023-09-28 23:45:48,115 log 15592 11760 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 90, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 138, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute '_meta'
ERROR 2023-09-28 23:45:48,116 basehttp 15592 11760 "POST /account/login HTTP/1.1" 500 79477
INFO 2023-09-28 23:46:03,944 views 15592 11760 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:46:04,228 views 15592 11760 Login successful
ERROR 2023-09-28 23:46:04,250 log 15592 11760 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 90, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 138, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute '_meta'
ERROR 2023-09-28 23:46:04,251 basehttp 15592 11760 "POST /account/login HTTP/1.1" 500 79477
INFO 2023-09-28 23:46:30,454 autoreload 15592 6016 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:46:30,952 autoreload 19100 10436 Watching for file changes with StatReloader
INFO 2023-09-28 23:46:33,136 views 19100 8936 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:46:33,420 views 19100 8936 Login successful
ERROR 2023-09-28 23:46:33,461 log 19100 8936 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 91, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 138, in login
    request.session[SESSION_KEY] = user._meta.pk.value_to_string(user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\utils\functional.py", line 268, in inner
    return func(_wrapped, *args)
AttributeError: 'AnonymousUser' object has no attribute '_meta'
ERROR 2023-09-28 23:46:33,464 basehttp 19100 8936 "POST /account/login HTTP/1.1" 500 79477
INFO 2023-09-28 23:53:20,093 autoreload 19100 10436 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:53:20,601 autoreload 4372 10516 Watching for file changes with StatReloader
INFO 2023-09-28 23:53:22,770 views 4372 3904 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:53:22,772 views 4372 3904 Login successful
ERROR 2023-09-28 23:53:22,813 log 4372 3904 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 91, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 144, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\base.py", line 797, in save
    raise ValueError(
ValueError: The following fields do not exist in this model, are m2m fields, or are non-concrete fields: last_login
ERROR 2023-09-28 23:53:22,816 basehttp 4372 3904 "POST /account/login HTTP/1.1" 500 93818
INFO 2023-09-28 23:53:52,465 autoreload 4372 10516 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:53:52,940 autoreload 15524 8312 Watching for file changes with StatReloader
INFO 2023-09-28 23:53:53,143 basehttp 15524 10268 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:53:55,160 views 15524 10268 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:53:55,163 views 15524 10268 Login successful
INFO 2023-09-28 23:53:55,177 basehttp 15524 10268 "POST /account/login HTTP/1.1" 200 3701
INFO 2023-09-28 23:54:16,086 views 15524 10268 Index page accessed
INFO 2023-09-28 23:54:16,092 basehttp 15524 10268 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 23:54:23,479 basehttp 15524 10268 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:54:26,315 basehttp 15524 10268 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:54:34,858 basehttp 15524 10268 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:54:36,096 basehttp 15524 10268 "GET /account/registration/ HTTP/1.1" 200 4035
INFO 2023-09-28 23:54:37,521 views 15524 10268 Index page accessed
INFO 2023-09-28 23:54:37,524 basehttp 15524 10268 "GET / HTTP/1.1" 200 10730
INFO 2023-09-28 23:55:21,171 autoreload 15524 8312 E:\pythonProject\djangoGB\store\views.py changed, reloading.
INFO 2023-09-28 23:55:21,645 autoreload 16496 16600 Watching for file changes with StatReloader
INFO 2023-09-28 23:55:22,863 basehttp 16496 10336 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:55:34,968 views 16496 10336 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:55:34,971 views 16496 10336 Login successful
INFO 2023-09-28 23:55:34,982 basehttp 16496 10336 "POST /account/login HTTP/1.1" 200 3701
INFO 2023-09-28 23:55:38,883 views 16496 10336 Index page accessed
ERROR 2023-09-28 23:55:38,915 log 16496 10336 Internal Server Error: /
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\store\views.py", line 20, in index
    print(user.is_authenticated)
NameError: name 'user' is not defined
ERROR 2023-09-28 23:55:38,917 basehttp 16496 10336 "GET / HTTP/1.1" 500 68612
WARNING 2023-09-28 23:55:53,479 log 16496 10336 Forbidden (CSRF token from POST incorrect.): /account/login
WARNING 2023-09-28 23:55:53,480 basehttp 16496 10336 "POST /account/login HTTP/1.1" 403 2560
INFO 2023-09-28 23:55:54,828 basehttp 16496 10336 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:55:56,625 basehttp 16496 10336 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-28 23:56:39,448 autoreload 16496 16600 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:56:39,958 autoreload 10652 15768 Watching for file changes with StatReloader
INFO 2023-09-28 23:56:56,994 autoreload 10652 15768 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-28 23:56:57,468 autoreload 11612 11508 Watching for file changes with StatReloader
INFO 2023-09-28 23:57:04,284 views 11612 17308 Try login: email='test@test.ru', password='test'.
INFO 2023-09-28 23:57:04,286 views 11612 17308 Login successful
INFO 2023-09-28 23:57:04,309 basehttp 11612 17308 "POST /account/login HTTP/1.1" 200 3701
INFO 2023-09-29 00:18:58,285 autoreload 11612 11508 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-29 00:18:58,754 autoreload 14140 14372 Watching for file changes with StatReloader
INFO 2023-09-29 00:19:01,819 views 14140 17352 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 00:19:01,821 views 14140 17352 Login successful
ERROR 2023-09-29 00:19:01,858 log 14140 17352 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 91, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 144, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\base.py", line 797, in save
    raise ValueError(
ValueError: The following fields do not exist in this model, are m2m fields, or are non-concrete fields: last_login
ERROR 2023-09-29 00:19:01,861 basehttp 14140 17352 "POST /account/login HTTP/1.1" 500 93967
INFO 2023-09-29 00:19:23,310 autoreload 14140 14372 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-29 00:19:23,794 autoreload 3328 16900 Watching for file changes with StatReloader
INFO 2023-09-29 00:19:24,534 basehttp 3328 12080 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-29 00:19:26,811 views 3328 12080 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 00:19:26,814 views 3328 12080 Login successful
ERROR 2023-09-29 00:19:26,848 log 3328 12080 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 91, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 144, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\base.py", line 797, in save
    raise ValueError(
ValueError: The following fields do not exist in this model, are m2m fields, or are non-concrete fields: last_login
ERROR 2023-09-29 00:19:26,851 basehttp 3328 12080 "POST /account/login HTTP/1.1" 500 93967
INFO 2023-09-29 00:22:32,774 basehttp 3328 12080 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-29 00:22:34,881 views 3328 12080 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 00:22:34,883 views 3328 12080 Login successful
ERROR 2023-09-29 00:22:34,905 log 3328 12080 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 91, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 144, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\base.py", line 797, in save
    raise ValueError(
ValueError: The following fields do not exist in this model, are m2m fields, or are non-concrete fields: last_login
ERROR 2023-09-29 00:22:34,907 basehttp 3328 12080 "POST /account/login HTTP/1.1" 500 93967
INFO 2023-09-29 00:22:55,475 autoreload 16948 2112 Watching for file changes with StatReloader
INFO 2023-09-29 00:23:03,989 basehttp 16948 15668 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-29 00:23:05,639 views 16948 15668 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 00:23:05,642 views 16948 15668 Login successful
ERROR 2023-09-29 00:23:05,677 log 16948 15668 Internal Server Error: /account/login
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 91, in login_form
    login(request, user, backend='E:\\pythonProject\\djangoGB\\account\\views.py')
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\__init__.py", line 144, in login
    user_logged_in.send(sender=user.__class__, request=request, user=user)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 176, in send
    return [
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\dispatch\dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\contrib\auth\models.py", line 23, in update_last_login
    user.save(update_fields=["last_login"])
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\db\models\base.py", line 797, in save
    raise ValueError(
ValueError: The following fields do not exist in this model, are m2m fields, or are non-concrete fields: last_login
ERROR 2023-09-29 00:23:05,680 basehttp 16948 15668 "POST /account/login HTTP/1.1" 500 93967
INFO 2023-09-29 00:27:59,518 autoreload 15184 3928 Watching for file changes with StatReloader
INFO 2023-09-29 00:28:20,575 autoreload 15184 3928 E:\pythonProject\djangoGB\store\models.py changed, reloading.
INFO 2023-09-29 00:28:21,027 autoreload 7312 16000 Watching for file changes with StatReloader
INFO 2023-09-29 00:28:23,641 basehttp 7312 11904 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-29 00:28:25,578 views 7312 11904 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 00:28:25,581 views 7312 11904 Login successful
INFO 2023-09-29 00:28:25,592 basehttp 7312 11904 "POST /account/login HTTP/1.1" 200 3701
INFO 2023-09-29 00:28:27,098 views 7312 11904 Index page accessed
ERROR 2023-09-29 00:28:27,130 log 7312 11904 Internal Server Error: /
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\store\views.py", line 20, in index
    print(user.is_authenticated)
NameError: name 'user' is not defined
ERROR 2023-09-29 00:28:27,131 basehttp 7312 11904 "GET / HTTP/1.1" 500 68612
INFO 2023-09-29 00:28:36,052 basehttp 7312 11904 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-29 00:28:38,679 views 7312 11904 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 00:28:38,681 views 7312 11904 Login successful
INFO 2023-09-29 00:28:38,692 basehttp 7312 11904 "POST /account/login HTTP/1.1" 200 3701
INFO 2023-09-29 00:29:58,853 autoreload 7312 16000 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-29 00:29:59,322 autoreload 12732 14716 Watching for file changes with StatReloader
INFO 2023-09-29 00:30:02,260 views 12732 19260 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 00:30:02,262 views 12732 19260 Login successful
INFO 2023-09-29 00:30:02,283 basehttp 12732 19260 "POST /account/login HTTP/1.1" 200 3701
INFO 2023-09-29 00:30:05,731 views 12732 19260 Index page accessed
ERROR 2023-09-29 00:30:05,767 log 12732 19260 Internal Server Error: /
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\store\views.py", line 20, in index
    print(user.is_authenticated)
NameError: name 'user' is not defined
ERROR 2023-09-29 00:30:05,768 basehttp 12732 19260 "GET / HTTP/1.1" 500 68612
INFO 2023-09-29 00:30:18,777 autoreload 12732 14716 E:\pythonProject\djangoGB\store\views.py changed, reloading.
INFO 2023-09-29 00:30:19,388 autoreload 19236 13008 Watching for file changes with StatReloader
INFO 2023-09-29 00:30:20,314 views 19236 12904 Index page accessed
INFO 2023-09-29 00:30:20,325 basehttp 19236 12904 "GET / HTTP/1.1" 200 10730
INFO 2023-09-29 00:30:21,615 basehttp 19236 12904 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-29 00:30:29,965 views 19236 12904 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 00:30:29,968 views 19236 12904 Login successful
INFO 2023-09-29 00:30:29,982 basehttp 19236 12904 "POST /account/login HTTP/1.1" 200 3701
INFO 2023-09-29 00:30:31,524 views 19236 12904 Index page accessed
INFO 2023-09-29 00:30:31,533 basehttp 19236 12904 "GET / HTTP/1.1" 200 10730
INFO 2023-09-29 00:30:54,240 autoreload 19236 13008 E:\pythonProject\djangoGB\store\views.py changed, reloading.
INFO 2023-09-29 00:30:54,701 autoreload 9472 6632 Watching for file changes with StatReloader
WARNING 2023-09-29 00:30:56,079 log 9472 9784 Forbidden (CSRF token from POST incorrect.): /account/login
WARNING 2023-09-29 00:30:56,080 basehttp 9472 9784 "POST /account/login HTTP/1.1" 403 2560
INFO 2023-09-29 00:30:57,282 basehttp 9472 9784 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-29 00:30:58,368 basehttp 9472 9784 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-29 00:31:03,740 views 9472 9784 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 00:31:03,743 views 9472 9784 Login successful
INFO 2023-09-29 00:31:03,758 basehttp 9472 9784 "POST /account/login HTTP/1.1" 200 3701
INFO 2023-09-29 00:31:06,187 views 9472 9784 Index page accessed
INFO 2023-09-29 00:31:06,198 basehttp 9472 9784 "GET / HTTP/1.1" 200 10730
INFO 2023-09-29 00:31:13,943 basehttp 9472 9784 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-29 00:34:49,459 autoreload 9472 6632 E:\pythonProject\djangoGB\djangoGB\settings.py changed, reloading.
INFO 2023-09-29 00:34:50,112 autoreload 1508 15100 Watching for file changes with StatReloader
INFO 2023-09-29 00:34:56,582 views 1508 9364 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 00:34:56,585 views 1508 9364 Login successful
INFO 2023-09-29 00:34:56,612 basehttp 1508 9364 "POST /account/login HTTP/1.1" 200 3701
INFO 2023-09-29 00:34:59,915 views 1508 9364 Index page accessed
INFO 2023-09-29 00:34:59,926 basehttp 1508 9364 "GET / HTTP/1.1" 200 10730
INFO 2023-09-29 00:35:02,852 basehttp 1508 9364 "GET /account/login HTTP/1.1" 200 3629
INFO 2023-09-29 00:35:55,567 autoreload 1508 15100 E:\pythonProject\djangoGB\djangoGB\settings.py changed, reloading.
INFO 2023-09-29 00:35:56,022 autoreload 12180 14540 Watching for file changes with StatReloader
INFO 2023-09-29 00:36:08,788 autoreload 12180 14540 E:\pythonProject\djangoGB\djangoGB\settings.py changed, reloading.
INFO 2023-09-29 00:36:09,190 autoreload 13236 19248 Watching for file changes with StatReloader
INFO 2023-09-29 00:36:43,604 autoreload 13236 19248 E:\pythonProject\djangoGB\djangoGB\settings.py changed, reloading.
INFO 2023-09-29 00:36:43,981 autoreload 1240 12580 Watching for file changes with StatReloader
INFO 2023-09-29 00:37:23,573 autoreload 1240 12580 E:\pythonProject\djangoGB\djangoGB\settings.py changed, reloading.
INFO 2023-09-29 00:37:23,984 autoreload 19204 1660 Watching for file changes with StatReloader
INFO 2023-09-29 00:37:32,491 autoreload 19204 1660 E:\pythonProject\djangoGB\djangoGB\settings.py changed, reloading.
INFO 2023-09-29 00:37:32,941 autoreload 9864 17992 Watching for file changes with StatReloader
INFO 2023-09-29 00:39:02,612 autoreload 9864 17992 E:\pythonProject\djangoGB\store\models.py changed, reloading.
INFO 2023-09-29 00:39:03,125 autoreload 5184 12104 Watching for file changes with StatReloader
INFO 2023-09-29 00:39:52,121 autoreload 5184 12104 E:\pythonProject\djangoGB\store\models.py changed, reloading.
INFO 2023-09-29 00:39:52,594 autoreload 568 18400 Watching for file changes with StatReloader
INFO 2023-09-29 00:39:57,705 views 568 18128 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 00:39:57,707 views 568 18128 Login successful
INFO 2023-09-29 00:39:57,732 basehttp 568 18128 "POST /account/login HTTP/1.1" 200 3701
INFO 2023-09-29 00:40:00,262 views 568 18128 Index page accessed
INFO 2023-09-29 00:40:00,269 basehttp 568 18128 "GET / HTTP/1.1" 200 10780
INFO 2023-09-29 00:40:02,988 views 568 18128 Index page accessed
INFO 2023-09-29 00:40:02,992 basehttp 568 18128 "GET / HTTP/1.1" 200 10780
INFO 2023-09-29 00:40:04,920 views 568 18128 Index page accessed
INFO 2023-09-29 00:40:04,924 basehttp 568 18128 "GET / HTTP/1.1" 200 10780
INFO 2023-09-29 00:40:05,818 views 568 18128 Index page accessed
INFO 2023-09-29 00:40:05,822 basehttp 568 18128 "GET / HTTP/1.1" 200 10780
INFO 2023-09-29 00:40:07,192 views 568 18128 Index page accessed
INFO 2023-09-29 00:40:07,196 basehttp 568 18128 "GET / HTTP/1.1" 200 10780
INFO 2023-09-29 00:40:08,284 views 568 18128 Index page accessed
INFO 2023-09-29 00:40:08,288 basehttp 568 18128 "GET / HTTP/1.1" 200 10780
INFO 2023-09-29 00:40:08,967 views 568 18128 Index page accessed
INFO 2023-09-29 00:40:08,971 basehttp 568 18128 "GET / HTTP/1.1" 200 10780
INFO 2023-09-29 00:41:12,692 autoreload 568 18400 E:\pythonProject\djangoGB\store\models.py changed, reloading.
INFO 2023-09-29 00:41:13,154 autoreload 17600 18040 Watching for file changes with StatReloader
INFO 2023-09-29 00:41:13,468 views 17600 3120 Index page accessed
INFO 2023-09-29 00:41:13,483 basehttp 17600 3120 "GET / HTTP/1.1" 200 10780
INFO 2023-09-29 00:41:15,686 views 17600 3120 Index page accessed
INFO 2023-09-29 00:41:15,690 basehttp 17600 3120 "GET / HTTP/1.1" 200 10780
INFO 2023-09-29 00:41:54,075 views 17600 3120 Index page accessed
INFO 2023-09-29 00:41:54,079 basehttp 17600 3120 "GET / HTTP/1.1" 200 10780
INFO 2023-09-29 00:41:54,526 views 17600 3120 Index page accessed
INFO 2023-09-29 00:41:54,530 basehttp 17600 3120 "GET / HTTP/1.1" 200 10780
INFO 2023-09-29 00:44:27,653 autoreload 17600 18040 E:\pythonProject\djangoGB\djangoGB\settings.py changed, reloading.
INFO 2023-09-29 00:44:28,146 autoreload 444 18896 Watching for file changes with StatReloader
INFO 2023-09-29 00:44:30,709 views 444 11756 Index page accessed
INFO 2023-09-29 00:44:30,721 basehttp 444 11756 "GET / HTTP/1.1" 200 10780
INFO 2023-09-29 00:44:31,867 views 444 11756 Index page accessed
INFO 2023-09-29 00:44:31,871 basehttp 444 11756 "GET / HTTP/1.1" 200 10780
INFO 2023-09-29 00:48:16,284 autoreload 444 18896 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-29 00:48:16,762 autoreload 8892 1952 Watching for file changes with StatReloader
INFO 2023-09-29 00:48:27,767 views 8892 9744 Index page accessed
INFO 2023-09-29 00:48:27,780 basehttp 8892 9744 "GET / HTTP/1.1" 200 10780
INFO 2023-09-29 00:48:28,828 views 8892 9744 Index page accessed
INFO 2023-09-29 00:48:28,832 basehttp 8892 9744 "GET / HTTP/1.1" 200 10780
INFO 2023-09-29 00:48:48,028 views 8892 9744 Index page accessed
ERROR 2023-09-29 00:48:48,089 log 8892 9744 Internal Server Error: /
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\store\views.py", line 22, in index
    return render(request, 'store/index.html', {"context": context})
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'logout' not found. 'logout' is not a valid view function or pattern name.
ERROR 2023-09-29 00:48:48,093 basehttp 8892 9744 "GET / HTTP/1.1" 500 201172
INFO 2023-09-29 00:49:00,474 views 8892 9744 Index page accessed
ERROR 2023-09-29 00:49:00,519 log 8892 9744 Internal Server Error: /
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\store\views.py", line 22, in index
    return render(request, 'store/index.html', {"context": context})
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'logout_user' not found. 'logout_user' is not a valid view function or pattern name.
ERROR 2023-09-29 00:49:00,522 basehttp 8892 9744 "GET / HTTP/1.1" 500 201439
INFO 2023-09-29 00:49:51,434 autoreload 8892 1952 E:\pythonProject\djangoGB\account\urls.py changed, reloading.
INFO 2023-09-29 00:49:51,902 autoreload 7896 10700 Watching for file changes with StatReloader
INFO 2023-09-29 00:49:52,204 views 7896 17832 Index page accessed
INFO 2023-09-29 00:49:52,217 basehttp 7896 17832 "GET / HTTP/1.1" 200 10789
ERROR 2023-09-29 00:49:53,449 log 7896 17832 Internal Server Error: /account/
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view account.views.logout_user didn't return an HttpResponse object. It returned None instead.
ERROR 2023-09-29 00:49:53,450 basehttp 7896 17832 "GET /account/ HTTP/1.1" 500 69938
INFO 2023-09-29 00:50:52,936 autoreload 7896 10700 E:\pythonProject\djangoGB\djangoGB\settings.py changed, reloading.
INFO 2023-09-29 00:50:53,436 autoreload 15524 16348 Watching for file changes with StatReloader
ERROR 2023-09-29 00:50:55,308 log 15524 12732 Internal Server Error: /account/
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view account.views.logout_user didn't return an HttpResponse object. It returned None instead.
ERROR 2023-09-29 00:50:55,309 basehttp 15524 12732 "GET /account/ HTTP/1.1" 500 69787
INFO 2023-09-29 00:51:34,713 autoreload 15524 16348 E:\pythonProject\djangoGB\djangoGB\settings.py changed, reloading.
INFO 2023-09-29 00:51:35,183 autoreload 11772 16536 Watching for file changes with StatReloader
ERROR 2023-09-29 00:51:37,145 log 11772 13432 Internal Server Error: /account/
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view account.views.logout_user didn't return an HttpResponse object. It returned None instead.
ERROR 2023-09-29 00:51:37,147 basehttp 11772 13432 "GET /account/ HTTP/1.1" 500 69793
INFO 2023-09-29 00:52:08,145 autoreload 11772 16536 E:\pythonProject\djangoGB\account\urls.py changed, reloading.
INFO 2023-09-29 00:52:08,629 autoreload 16212 11808 Watching for file changes with StatReloader
WARNING 2023-09-29 00:52:09,840 log 16212 13336 Not Found: /account/
WARNING 2023-09-29 00:52:09,840 basehttp 16212 13336 "GET /account/ HTTP/1.1" 404 4293
INFO 2023-09-29 00:52:59,135 autoreload 16212 11808 E:\pythonProject\djangoGB\account\urls.py changed, reloading.
INFO 2023-09-29 00:52:59,592 autoreload 11100 5172 Watching for file changes with StatReloader
WARNING 2023-09-29 00:53:01,131 log 11100 12860 Not Found: /account/
WARNING 2023-09-29 00:53:01,131 basehttp 11100 12860 "GET /account/ HTTP/1.1" 404 4294
INFO 2023-09-29 00:53:15,771 autoreload 11100 5172 E:\pythonProject\djangoGB\djangoGB\settings.py changed, reloading.
INFO 2023-09-29 00:53:16,241 autoreload 16912 14632 Watching for file changes with StatReloader
WARNING 2023-09-29 00:53:21,280 log 16912 3724 Not Found: /account/
WARNING 2023-09-29 00:53:21,281 basehttp 16912 3724 "GET /account/ HTTP/1.1" 404 4294
INFO 2023-09-29 00:53:47,031 autoreload 16912 14632 E:\pythonProject\djangoGB\account\urls.py changed, reloading.
INFO 2023-09-29 00:53:47,501 autoreload 4552 17588 Watching for file changes with StatReloader
ERROR 2023-09-29 00:53:48,145 log 4552 844 Internal Server Error: /account/
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view account.views.logout_user didn't return an HttpResponse object. It returned None instead.
ERROR 2023-09-29 00:53:48,146 basehttp 4552 844 "GET /account/ HTTP/1.1" 500 69803
ERROR 2023-09-29 00:53:51,200 log 4552 844 Internal Server Error: /account/
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view account.views.logout_user didn't return an HttpResponse object. It returned None instead.
ERROR 2023-09-29 00:53:51,201 basehttp 4552 844 "GET /account/ HTTP/1.1" 500 69803
INFO 2023-09-29 00:54:02,056 views 4552 844 Index page accessed
INFO 2023-09-29 00:54:02,062 basehttp 4552 844 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 00:54:03,640 basehttp 4552 844 "GET /account/login/ HTTP/1.1" 200 3630
INFO 2023-09-29 00:54:10,423 views 4552 844 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 00:54:10,426 views 4552 844 Login successful
INFO 2023-09-29 00:54:10,440 basehttp 4552 844 "POST /account/login/ HTTP/1.1" 200 3710
INFO 2023-09-29 00:54:12,634 views 4552 844 Index page accessed
INFO 2023-09-29 00:54:12,639 basehttp 4552 844 "GET / HTTP/1.1" 200 10789
ERROR 2023-09-29 00:54:13,821 log 4552 844 Internal Server Error: /account/
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view account.views.logout_user didn't return an HttpResponse object. It returned None instead.
ERROR 2023-09-29 00:54:13,822 basehttp 4552 844 "GET /account/ HTTP/1.1" 500 69952
INFO 2023-09-29 00:54:21,254 views 4552 844 Index page accessed
INFO 2023-09-29 00:54:21,257 basehttp 4552 844 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 00:54:27,683 autoreload 4552 17588 E:\pythonProject\djangoGB\djangoGB\settings.py changed, reloading.
INFO 2023-09-29 00:54:28,146 autoreload 17800 16904 Watching for file changes with StatReloader
INFO 2023-09-29 00:54:28,587 basehttp 17800 1160 "GET /account/login/ HTTP/1.1" 200 3630
INFO 2023-09-29 00:54:34,729 views 17800 1160 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 00:54:34,731 views 17800 1160 Login successful
INFO 2023-09-29 00:54:34,745 basehttp 17800 1160 "POST /account/login/ HTTP/1.1" 200 3710
INFO 2023-09-29 00:54:36,172 views 17800 1160 Index page accessed
INFO 2023-09-29 00:54:36,179 basehttp 17800 1160 "GET / HTTP/1.1" 200 10789
INFO 2023-09-29 00:54:36,739 views 17800 1160 Index page accessed
INFO 2023-09-29 00:54:36,743 basehttp 17800 1160 "GET / HTTP/1.1" 200 10789
DEBUG 2023-09-29 00:54:38,570 views 17800 1160 About page accessed
INFO 2023-09-29 00:54:38,574 basehttp 17800 1160 "GET /about/ HTTP/1.1" 200 2943
ERROR 2023-09-29 00:54:40,337 log 17800 1160 Internal Server Error: /account/
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view account.views.logout_user didn't return an HttpResponse object. It returned None instead.
ERROR 2023-09-29 00:54:40,338 basehttp 17800 1160 "GET /account/ HTTP/1.1" 500 69942
INFO 2023-09-29 00:58:47,592 autoreload 17800 16904 E:\pythonProject\djangoGB\account\urls.py changed, reloading.
INFO 2023-09-29 00:58:48,081 autoreload 8836 2252 Watching for file changes with StatReloader
DEBUG 2023-09-29 00:58:48,189 views 8836 13432 About page accessed
INFO 2023-09-29 00:58:48,197 basehttp 8836 13432 "GET /about/ HTTP/1.1" 200 2885
INFO 2023-09-29 00:58:49,178 views 8836 13432 Index page accessed
INFO 2023-09-29 00:58:49,184 basehttp 8836 13432 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 00:58:50,650 basehttp 8836 13432 "GET /account/login/ HTTP/1.1" 200 3630
INFO 2023-09-29 00:58:56,327 views 8836 13432 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 00:58:56,331 views 8836 13432 Login successful
INFO 2023-09-29 00:58:56,345 basehttp 8836 13432 "POST /account/login/ HTTP/1.1" 200 3716
INFO 2023-09-29 00:58:58,520 views 8836 13432 Index page accessed
INFO 2023-09-29 00:58:58,524 basehttp 8836 13432 "GET / HTTP/1.1" 200 10795
INFO 2023-09-29 00:58:59,634 basehttp 8836 13432 "GET /account/login/ HTTP/1.1" 200 3694
INFO 2023-09-29 00:59:12,164 views 8836 13432 Index page accessed
INFO 2023-09-29 00:59:12,168 basehttp 8836 13432 "GET / HTTP/1.1" 200 10795
INFO 2023-09-29 00:59:12,533 autoreload 8836 2252 E:\pythonProject\djangoGB\djangoGB\settings.py changed, reloading.
INFO 2023-09-29 00:59:12,990 autoreload 7912 2668 Watching for file changes with StatReloader
INFO 2023-09-29 00:59:14,384 views 7912 6028 Index page accessed
INFO 2023-09-29 00:59:14,398 basehttp 7912 6028 "GET / HTTP/1.1" 200 10795
INFO 2023-09-29 00:59:16,501 basehttp 7912 6028 "GET /account/login/ HTTP/1.1" 200 3694
INFO 2023-09-29 00:59:17,795 views 7912 6028 Index page accessed
INFO 2023-09-29 00:59:17,799 basehttp 7912 6028 "GET / HTTP/1.1" 200 10795
INFO 2023-09-29 00:59:18,756 basehttp 7912 6028 "GET /account/login/ HTTP/1.1" 200 3694
INFO 2023-09-29 00:59:19,344 basehttp 7912 6028 "GET /account/login/ HTTP/1.1" 200 3694
INFO 2023-09-29 00:59:20,446 views 7912 6028 Index page accessed
INFO 2023-09-29 00:59:20,450 basehttp 7912 6028 "GET / HTTP/1.1" 200 10795
INFO 2023-09-29 00:59:20,859 views 7912 6028 Index page accessed
INFO 2023-09-29 00:59:20,863 basehttp 7912 6028 "GET / HTTP/1.1" 200 10795
INFO 2023-09-29 01:00:00,448 autoreload 7912 2668 E:\pythonProject\djangoGB\account\urls.py changed, reloading.
INFO 2023-09-29 01:00:00,928 autoreload 18296 11100 Watching for file changes with StatReloader
INFO 2023-09-29 01:00:01,065 views 18296 8024 Index page accessed
INFO 2023-09-29 01:00:01,079 basehttp 18296 8024 "GET / HTTP/1.1" 200 10795
INFO 2023-09-29 01:00:02,032 basehttp 18296 8024 "GET /account/login/ HTTP/1.1" 200 3694
INFO 2023-09-29 01:00:04,204 basehttp 18296 8024 "GET /account/login/ HTTP/1.1" 200 3694
INFO 2023-09-29 01:00:04,677 basehttp 18296 8024 "GET /account/login/ HTTP/1.1" 200 3694
INFO 2023-09-29 01:00:05,559 views 18296 8024 Index page accessed
INFO 2023-09-29 01:00:05,563 basehttp 18296 8024 "GET / HTTP/1.1" 200 10795
INFO 2023-09-29 01:00:13,916 autoreload 18296 11100 E:\pythonProject\djangoGB\djangoGB\settings.py changed, reloading.
INFO 2023-09-29 01:00:14,393 autoreload 11276 12104 Watching for file changes with StatReloader
INFO 2023-09-29 01:00:14,667 views 11276 10664 Index page accessed
INFO 2023-09-29 01:00:14,680 basehttp 11276 10664 "GET / HTTP/1.1" 200 10795
INFO 2023-09-29 01:00:15,410 basehttp 11276 10664 "GET /account/login/ HTTP/1.1" 200 3694
INFO 2023-09-29 01:00:16,351 basehttp 11276 10664 "GET /account/login/ HTTP/1.1" 200 3694
INFO 2023-09-29 01:00:17,220 views 11276 10664 Index page accessed
INFO 2023-09-29 01:00:17,224 basehttp 11276 10664 "GET / HTTP/1.1" 200 10795
INFO 2023-09-29 01:00:17,706 views 11276 10664 Index page accessed
INFO 2023-09-29 01:00:17,710 basehttp 11276 10664 "GET / HTTP/1.1" 200 10795
INFO 2023-09-29 01:00:18,301 basehttp 11276 10664 "GET /account/login/ HTTP/1.1" 200 3694
INFO 2023-09-29 01:00:25,212 autoreload 11276 12104 E:\pythonProject\djangoGB\account\urls.py changed, reloading.
INFO 2023-09-29 01:00:25,680 autoreload 3220 7580 Watching for file changes with StatReloader
INFO 2023-09-29 01:00:25,941 views 3220 9332 Index page accessed
INFO 2023-09-29 01:00:25,954 basehttp 3220 9332 "GET / HTTP/1.1" 200 10789
ERROR 2023-09-29 01:00:27,074 log 3220 9332 Internal Server Error: /account/
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view account.views.logout_user didn't return an HttpResponse object. It returned None instead.
ERROR 2023-09-29 01:00:27,075 basehttp 3220 9332 "GET /account/ HTTP/1.1" 500 69936
INFO 2023-09-29 01:00:29,203 views 3220 9332 Index page accessed
INFO 2023-09-29 01:00:29,207 basehttp 3220 9332 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 01:00:30,071 views 3220 9332 Index page accessed
INFO 2023-09-29 01:00:30,074 basehttp 3220 9332 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 01:01:23,610 views 3220 9332 Index page accessed
INFO 2023-09-29 01:01:23,613 basehttp 3220 9332 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 01:01:23,716 autoreload 3220 7580 E:\pythonProject\djangoGB\account\urls.py changed, reloading.
INFO 2023-09-29 01:01:24,188 autoreload 8528 3292 Watching for file changes with StatReloader
INFO 2023-09-29 01:01:25,177 views 8528 632 Index page accessed
INFO 2023-09-29 01:01:25,189 basehttp 8528 632 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 01:01:25,906 basehttp 8528 632 "GET /account/login/ HTTP/1.1" 200 3630
INFO 2023-09-29 01:01:34,194 views 8528 632 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 01:01:34,197 views 8528 632 Login successful
INFO 2023-09-29 01:01:34,211 basehttp 8528 632 "POST /account/login/ HTTP/1.1" 200 3711
INFO 2023-09-29 01:01:36,628 views 8528 632 Index page accessed
INFO 2023-09-29 01:01:36,633 basehttp 8528 632 "GET / HTTP/1.1" 200 10790
ERROR 2023-09-29 01:01:37,584 log 8528 632 Internal Server Error: /account//
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view account.views.logout_user didn't return an HttpResponse object. It returned None instead.
ERROR 2023-09-29 01:01:37,585 basehttp 8528 632 "GET /account// HTTP/1.1" 500 69945
INFO 2023-09-29 01:01:43,526 autoreload 8528 3292 E:\pythonProject\djangoGB\account\urls.py changed, reloading.
INFO 2023-09-29 01:01:43,995 autoreload 16360 17184 Watching for file changes with StatReloader
WARNING 2023-09-29 01:01:44,221 log 16360 18568 Not Found: /account//
WARNING 2023-09-29 01:01:44,222 basehttp 16360 18568 "GET /account// HTTP/1.1" 404 4297
INFO 2023-09-29 01:01:49,181 views 16360 18568 Index page accessed
INFO 2023-09-29 01:01:49,190 basehttp 16360 18568 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 01:01:50,342 basehttp 16360 18568 "GET /account/login/ HTTP/1.1" 200 3630
INFO 2023-09-29 01:01:55,799 views 16360 18568 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 01:01:55,802 views 16360 18568 Login successful
INFO 2023-09-29 01:01:55,817 basehttp 16360 18568 "POST /account/login/ HTTP/1.1" 200 3710
INFO 2023-09-29 01:01:57,140 views 16360 18568 Index page accessed
INFO 2023-09-29 01:01:57,144 basehttp 16360 18568 "GET / HTTP/1.1" 200 10789
ERROR 2023-09-29 01:01:59,763 log 16360 18568 Internal Server Error: /account/
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view account.views.logout_user didn't return an HttpResponse object. It returned None instead.
ERROR 2023-09-29 01:01:59,764 basehttp 16360 18568 "GET /account/ HTTP/1.1" 500 69936
INFO 2023-09-29 01:02:04,563 views 16360 18568 Index page accessed
INFO 2023-09-29 01:02:04,567 basehttp 16360 18568 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 01:02:15,446 basehttp 16360 18568 "GET /account/login/ HTTP/1.1" 200 3630
INFO 2023-09-29 01:02:15,956 autoreload 16360 17184 E:\pythonProject\djangoGB\account\urls.py changed, reloading.
INFO 2023-09-29 01:02:16,437 autoreload 11712 6084 Watching for file changes with StatReloader
INFO 2023-09-29 01:02:20,429 views 11712 16916 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 01:02:20,431 views 11712 16916 Login successful
INFO 2023-09-29 01:02:20,456 basehttp 11712 16916 "POST /account/login/ HTTP/1.1" 200 3723
INFO 2023-09-29 01:02:21,789 views 11712 16916 Index page accessed
INFO 2023-09-29 01:02:21,796 basehttp 11712 16916 "GET / HTTP/1.1" 200 10802
INFO 2023-09-29 01:02:22,794 basehttp 11712 16916 "GET /account/registration/ HTTP/1.1" 200 4107
INFO 2023-09-29 01:02:26,645 views 11712 16916 Index page accessed
INFO 2023-09-29 01:02:26,650 basehttp 11712 16916 "GET / HTTP/1.1" 200 10802
INFO 2023-09-29 01:02:30,645 views 11712 16916 Index page accessed
INFO 2023-09-29 01:02:30,651 basehttp 11712 16916 "GET / HTTP/1.1" 200 10802
INFO 2023-09-29 01:02:31,227 basehttp 11712 16916 "GET /account/registration/ HTTP/1.1" 200 4107
INFO 2023-09-29 01:02:31,874 basehttp 11712 16916 "GET /account/registration/ HTTP/1.1" 200 4107
INFO 2023-09-29 01:02:32,379 basehttp 11712 16916 "GET /account/registration/ HTTP/1.1" 200 4107
INFO 2023-09-29 01:02:33,164 views 11712 16916 Index page accessed
INFO 2023-09-29 01:02:33,168 basehttp 11712 16916 "GET / HTTP/1.1" 200 10802
INFO 2023-09-29 01:03:17,661 autoreload 11712 6084 E:\pythonProject\djangoGB\account\urls.py changed, reloading.
INFO 2023-09-29 01:03:18,139 autoreload 3384 8328 Watching for file changes with StatReloader
INFO 2023-09-29 01:03:20,008 views 3384 13148 Index page accessed
INFO 2023-09-29 01:03:20,021 basehttp 3384 13148 "GET / HTTP/1.1" 200 10796
ERROR 2023-09-29 01:03:28,845 log 3384 13148 Internal Server Error: /account/logout/
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view account.views.logout_user didn't return an HttpResponse object. It returned None instead.
ERROR 2023-09-29 01:03:28,846 basehttp 3384 13148 "GET /account/logout/ HTTP/1.1" 500 69999
INFO 2023-09-29 01:07:49,475 autoreload 1720 15712 Watching for file changes with StatReloader
INFO 2023-09-29 01:07:52,463 views 1720 12204 Index page accessed
INFO 2023-09-29 01:07:52,474 basehttp 1720 12204 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 01:07:53,515 basehttp 1720 12204 "GET /account/login/ HTTP/1.1" 200 3630
INFO 2023-09-29 01:08:00,763 views 1720 12204 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 01:08:00,766 views 1720 12204 Login successful
INFO 2023-09-29 01:08:00,779 basehttp 1720 12204 "POST /account/login/ HTTP/1.1" 200 3717
INFO 2023-09-29 01:08:02,230 views 1720 12204 Index page accessed
INFO 2023-09-29 01:08:02,234 basehttp 1720 12204 "GET / HTTP/1.1" 200 10796
ERROR 2023-09-29 01:08:03,450 log 1720 12204 Internal Server Error: /account/logout/
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view account.views.logout_user didn't return an HttpResponse object. It returned None instead.
ERROR 2023-09-29 01:08:03,451 basehttp 1720 12204 "GET /account/logout/ HTTP/1.1" 500 70010
INFO 2023-09-29 01:08:54,933 autoreload 1720 15712 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-29 01:08:55,397 autoreload 11776 4016 Watching for file changes with StatReloader
INFO 2023-09-29 01:08:55,767 views 11776 4604 Index page accessed
INFO 2023-09-29 01:08:55,779 basehttp 11776 4604 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 01:08:56,812 basehttp 11776 4604 "GET /account/login/ HTTP/1.1" 200 3630
INFO 2023-09-29 01:09:02,124 views 11776 4604 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 01:09:02,126 views 11776 4604 Login successful
INFO 2023-09-29 01:09:02,139 basehttp 11776 4604 "POST /account/login/ HTTP/1.1" 200 3717
INFO 2023-09-29 01:09:03,661 views 11776 4604 Index page accessed
INFO 2023-09-29 01:09:03,665 basehttp 11776 4604 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 01:09:04,408 views 11776 4604 Index page accessed
INFO 2023-09-29 01:09:04,412 basehttp 11776 4604 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 01:09:04,921 views 11776 4604 Index page accessed
INFO 2023-09-29 01:09:04,926 basehttp 11776 4604 "GET / HTTP/1.1" 200 10796
ERROR 2023-09-29 01:09:05,592 log 11776 4604 Internal Server Error: /account/logout/
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 96, in logout_user
    return render(request, "account/logout.html")
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: account/logout.html
ERROR 2023-09-29 01:09:05,594 basehttp 11776 4604 "GET /account/logout/ HTTP/1.1" 500 83268
INFO 2023-09-29 01:09:41,184 views 11776 4604 Index page accessed
INFO 2023-09-29 01:09:41,188 basehttp 11776 4604 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 01:09:42,135 basehttp 11776 4604 "GET /account/login/ HTTP/1.1" 200 3630
INFO 2023-09-29 01:09:48,479 views 11776 4604 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 01:09:48,481 views 11776 4604 Login successful
INFO 2023-09-29 01:09:48,494 basehttp 11776 4604 "POST /account/login/ HTTP/1.1" 200 3717
INFO 2023-09-29 01:09:49,738 views 11776 4604 Index page accessed
INFO 2023-09-29 01:09:49,743 basehttp 11776 4604 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 01:09:50,260 views 11776 4604 Index page accessed
INFO 2023-09-29 01:09:50,264 basehttp 11776 4604 "GET / HTTP/1.1" 200 10796
ERROR 2023-09-29 01:09:50,994 log 11776 4604 Internal Server Error: /account/logout/
Traceback (most recent call last):
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\pythonProject\djangoGB\account\views.py", line 96, in logout_user
    return render(request, "account/logout.html")
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "E:\pythonProject\djangoGB\env\lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'login' not found. 'login' is not a valid view function or pattern name.
ERROR 2023-09-29 01:09:50,998 basehttp 11776 4604 "GET /account/logout/ HTTP/1.1" 500 162962
INFO 2023-09-29 01:10:35,427 views 11776 4604 Index page accessed
INFO 2023-09-29 01:10:35,430 basehttp 11776 4604 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 01:10:36,190 basehttp 11776 4604 "GET /account/login/ HTTP/1.1" 200 3630
INFO 2023-09-29 01:10:42,211 views 11776 4604 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 01:10:42,213 views 11776 4604 Login successful
INFO 2023-09-29 01:10:42,227 basehttp 11776 4604 "POST /account/login/ HTTP/1.1" 200 3717
INFO 2023-09-29 01:10:43,547 views 11776 4604 Index page accessed
INFO 2023-09-29 01:10:43,552 basehttp 11776 4604 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 01:10:44,131 views 11776 4604 Index page accessed
INFO 2023-09-29 01:10:44,135 basehttp 11776 4604 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 01:10:44,979 basehttp 11776 4604 "GET /account/logout/ HTTP/1.1" 200 2861
INFO 2023-09-29 01:10:49,130 views 11776 4604 Index page accessed
INFO 2023-09-29 01:10:49,133 basehttp 11776 4604 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 01:10:50,859 views 11776 4604 Index page accessed
INFO 2023-09-29 01:10:50,862 basehttp 11776 4604 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 01:10:52,424 basehttp 11776 4604 "GET /account/login/ HTTP/1.1" 200 3630
INFO 2023-09-29 01:11:00,276 views 11776 4604 Try login: email='test@test.ru', password='test\\'.
INFO 2023-09-29 01:11:00,279 views 11776 4604 Login failed
INFO 2023-09-29 01:11:00,282 basehttp 11776 4604 "POST /account/login/ HTTP/1.1" 200 3648
INFO 2023-09-29 01:11:08,586 views 11776 4604 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 01:11:08,588 views 11776 4604 Login successful
INFO 2023-09-29 01:11:08,602 basehttp 11776 4604 "POST /account/login/ HTTP/1.1" 200 3717
INFO 2023-09-29 01:11:10,201 views 11776 4604 Index page accessed
INFO 2023-09-29 01:11:10,205 basehttp 11776 4604 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 01:11:11,322 views 11776 4604 Index page accessed
INFO 2023-09-29 01:11:11,327 basehttp 11776 4604 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 01:11:13,744 views 11776 4604 Index page accessed
INFO 2023-09-29 01:11:13,749 basehttp 11776 4604 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 01:11:15,121 views 11776 4604 Index page accessed
INFO 2023-09-29 01:11:15,126 basehttp 11776 4604 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 01:11:15,606 views 11776 4604 Index page accessed
INFO 2023-09-29 01:11:15,610 basehttp 11776 4604 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 01:11:16,716 basehttp 11776 4604 "GET /account/logout/ HTTP/1.1" 200 2861
INFO 2023-09-29 01:12:31,269 basehttp 11776 4604 "GET /account/logout/ HTTP/1.1" 200 3029
INFO 2023-09-29 01:12:49,407 basehttp 11776 4604 "GET /account/logout/ HTTP/1.1" 200 3029
INFO 2023-09-29 01:12:50,849 basehttp 11776 4604 "GET /account/logout/ HTTP/1.1" 200 3029
INFO 2023-09-29 01:13:08,246 basehttp 11776 4604 "GET /account/logout/ HTTP/1.1" 200 3029
INFO 2023-09-29 01:13:08,940 basehttp 11776 4604 "GET /account/logout/ HTTP/1.1" 200 3051
INFO 2023-09-29 01:13:09,798 basehttp 11776 4604 "GET /account/logout/ HTTP/1.1" 200 3051
INFO 2023-09-29 01:13:33,206 basehttp 11776 4604 "GET /account/logout/ HTTP/1.1" 200 3029
INFO 2023-09-29 01:14:09,505 views 11776 4604 Index page accessed
INFO 2023-09-29 01:14:09,508 basehttp 11776 4604 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 01:14:11,148 basehttp 11776 4604 "GET /account/registration/ HTTP/1.1" 200 4036
INFO 2023-09-29 01:14:39,676 views 11776 4604 Registration new user: username='Pavel', email='pavel@admin.ru', password='admin'.
INFO 2023-09-29 01:14:39,684 basehttp 11776 4604 "POST /account/registration/ HTTP/1.1" 200 4072
INFO 2023-09-29 01:14:43,899 views 11776 4604 Index page accessed
INFO 2023-09-29 01:14:43,902 basehttp 11776 4604 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 01:14:44,912 basehttp 11776 4604 "GET /account/login/ HTTP/1.1" 200 3630
INFO 2023-09-29 01:14:51,814 views 11776 4604 Try login: email='pavel@admin.ru', password='admin'.
INFO 2023-09-29 01:14:51,816 views 11776 4604 Login successful
INFO 2023-09-29 01:14:51,844 basehttp 11776 4604 "POST /account/login/ HTTP/1.1" 200 3721
INFO 2023-09-29 01:14:53,216 views 11776 4604 Index page accessed
INFO 2023-09-29 01:14:53,220 basehttp 11776 4604 "GET / HTTP/1.1" 200 10797
INFO 2023-09-29 01:14:54,552 views 11776 4604 Index page accessed
INFO 2023-09-29 01:14:54,556 basehttp 11776 4604 "GET / HTTP/1.1" 200 10797
DEBUG 2023-09-29 01:14:56,069 views 11776 4604 About page accessed
INFO 2023-09-29 01:14:56,073 basehttp 11776 4604 "GET /about/ HTTP/1.1" 200 2951
DEBUG 2023-09-29 01:14:56,866 views 11776 4604 Info page accessed
INFO 2023-09-29 01:14:56,870 basehttp 11776 4604 "GET /info/ HTTP/1.1" 200 2952
INFO 2023-09-29 01:14:57,389 views 11776 4604 Index page accessed
INFO 2023-09-29 01:14:57,393 basehttp 11776 4604 "GET / HTTP/1.1" 200 10797
INFO 2023-09-29 01:14:58,902 basehttp 11776 4604 "GET /account/logout/ HTTP/1.1" 200 3029
INFO 2023-09-29 01:16:15,441 views 11776 4604 Index page accessed
INFO 2023-09-29 01:16:15,444 basehttp 11776 4604 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 01:16:15,511 autoreload 11776 4016 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-29 01:16:15,975 autoreload 4580 18276 Watching for file changes with StatReloader
INFO 2023-09-29 01:16:16,859 basehttp 4580 12292 "GET /account/login/ HTTP/1.1" 200 3630
INFO 2023-09-29 01:16:18,122 basehttp 4580 12292 "GET /account/registration/ HTTP/1.1" 200 4036
INFO 2023-09-29 01:16:33,929 views 4580 12292 Registration new user: username='Vova', email='vo@vo.da', password='vo'.
INFO 2023-09-29 01:16:33,949 basehttp 4580 12292 "POST /account/registration/ HTTP/1.1" 200 4130
INFO 2023-09-29 01:16:39,386 views 4580 12292 Index page accessed
INFO 2023-09-29 01:16:39,393 basehttp 4580 12292 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 01:16:40,719 views 4580 12292 Index page accessed
INFO 2023-09-29 01:16:40,724 basehttp 4580 12292 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 01:16:41,270 views 4580 12292 Index page accessed
INFO 2023-09-29 01:16:41,274 basehttp 4580 12292 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 01:17:01,260 views 4580 12292 Index page accessed
INFO 2023-09-29 01:17:01,265 basehttp 4580 12292 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 01:17:02,853 basehttp 4580 12292 "GET /account/logout/ HTTP/1.1" 200 3029
INFO 2023-09-29 01:17:04,610 basehttp 4580 12292 "GET /account/login/ HTTP/1.1" 200 3630
INFO 2023-09-29 01:17:12,802 views 4580 12292 Try login: email='vo@vo.da', password='vo'.
INFO 2023-09-29 01:17:12,806 views 4580 12292 Login successful
INFO 2023-09-29 01:17:12,821 basehttp 4580 12292 "POST /account/login/ HTTP/1.1" 200 3713
INFO 2023-09-29 01:17:18,378 views 4580 12292 Index page accessed
INFO 2023-09-29 01:17:18,383 basehttp 4580 12292 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 01:17:39,903 views 4580 12292 Index page accessed
INFO 2023-09-29 01:17:39,907 basehttp 4580 12292 "GET / HTTP/1.1" 200 10796
DEBUG 2023-09-29 01:17:41,424 views 4580 12292 About page accessed
INFO 2023-09-29 01:17:41,427 basehttp 4580 12292 "GET /about/ HTTP/1.1" 200 2950
DEBUG 2023-09-29 01:17:42,550 views 4580 12292 Info page accessed
INFO 2023-09-29 01:17:42,553 basehttp 4580 12292 "GET /info/ HTTP/1.1" 200 2951
DEBUG 2023-09-29 01:17:43,544 views 4580 12292 About page accessed
INFO 2023-09-29 01:17:43,548 basehttp 4580 12292 "GET /about/ HTTP/1.1" 200 2950
INFO 2023-09-29 01:17:44,056 views 4580 12292 Index page accessed
INFO 2023-09-29 01:17:44,060 basehttp 4580 12292 "GET / HTTP/1.1" 200 10796
DEBUG 2023-09-29 01:17:45,762 views 4580 12292 About page accessed
INFO 2023-09-29 01:17:45,766 basehttp 4580 12292 "GET /about/ HTTP/1.1" 200 2950
DEBUG 2023-09-29 01:18:09,566 views 4580 12292 About page accessed
INFO 2023-09-29 01:18:09,570 basehttp 4580 12292 "GET /about/ HTTP/1.1" 200 3005
DEBUG 2023-09-29 01:18:18,953 views 4580 12292 Info page accessed
INFO 2023-09-29 01:18:18,957 basehttp 4580 12292 "GET /info/ HTTP/1.1" 200 3006
DEBUG 2023-09-29 01:18:20,027 views 4580 12292 About page accessed
INFO 2023-09-29 01:18:20,031 basehttp 4580 12292 "GET /about/ HTTP/1.1" 200 3005
INFO 2023-09-29 01:18:21,139 views 4580 12292 Index page accessed
INFO 2023-09-29 01:18:21,144 basehttp 4580 12292 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 01:18:29,665 basehttp 4580 12292 "GET /account/logout/ HTTP/1.1" 200 3029
INFO 2023-09-29 01:18:31,421 views 4580 12292 Index page accessed
INFO 2023-09-29 01:18:31,424 basehttp 4580 12292 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 01:19:23,357 autoreload 4580 18276 E:\pythonProject\djangoGB\store\views.py changed, reloading.
INFO 2023-09-29 01:19:23,914 autoreload 1084 11584 Watching for file changes with StatReloader
INFO 2023-09-29 01:20:49,816 autoreload 1084 11584 E:\pythonProject\djangoGB\account\views.py changed, reloading.
INFO 2023-09-29 01:20:50,305 autoreload 17240 12572 Watching for file changes with StatReloader
INFO 2023-09-29 02:04:49,269 autoreload 14068 13576 Watching for file changes with StatReloader
INFO 2023-09-29 02:04:50,321 views 14068 8692 Index page accessed
INFO 2023-09-29 02:04:50,337 basehttp 14068 8692 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 02:04:51,940 views 14068 8692 Index page accessed
INFO 2023-09-29 02:04:51,942 basehttp 14068 8692 "GET / HTTP/1.1" 200 10731
DEBUG 2023-09-29 02:04:52,852 views 14068 8692 About page accessed
INFO 2023-09-29 02:04:52,854 basehttp 14068 8692 "GET /about/ HTTP/1.1" 200 2940
INFO 2023-09-29 02:04:53,763 views 14068 8692 Index page accessed
INFO 2023-09-29 02:04:53,766 basehttp 14068 8692 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 02:04:55,092 basehttp 14068 8692 "GET /account/login/ HTTP/1.1" 200 3630
INFO 2023-09-29 02:05:07,135 views 14068 8692 Try login: email='test@test.ru', password='test'.
INFO 2023-09-29 02:05:07,138 views 14068 8692 Login successful
INFO 2023-09-29 02:05:07,152 basehttp 14068 8692 "POST /account/login/ HTTP/1.1" 200 3717
INFO 2023-09-29 02:05:09,071 views 14068 8692 Index page accessed
INFO 2023-09-29 02:05:09,075 basehttp 14068 8692 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 02:05:09,576 views 14068 8692 Index page accessed
INFO 2023-09-29 02:05:09,579 basehttp 14068 8692 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 02:05:17,054 views 14068 8692 Index page accessed
INFO 2023-09-29 02:05:17,058 basehttp 14068 8692 "GET / HTTP/1.1" 200 10796
INFO 2023-09-29 02:05:17,736 basehttp 14068 8692 "GET /account/logout/ HTTP/1.1" 200 3029
INFO 2023-09-29 02:05:19,137 basehttp 14068 8692 "GET /account/login/ HTTP/1.1" 200 3630
INFO 2023-09-29 02:05:19,754 views 14068 8692 Index page accessed
INFO 2023-09-29 02:05:19,757 basehttp 14068 8692 "GET / HTTP/1.1" 200 10731
INFO 2023-09-29 02:05:20,055 views 14068 8692 Index page accessed
INFO 2023-09-29 02:05:20,057 basehttp 14068 8692 "GET / HTTP/1.1" 200 10731
